### ISSUE TITLE
Teacher Primer Screenshot

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#115]
@aaronsamuel137 said

>The only remaining privacy concern is that the way the page is set up now, somebody still could technically get the video link by viewing the page source - even when they are not logged in. I doubt most teachers would go through the trouble to do that however.

If this is an issue, I see two ways around it:

 1.   Don't show the video at all unless someone is logged in.
 2.  Just show a screenshot of the video instead when they are not logged in. (This option is more work since we'll have to take screenshots of every video and host them somewhere ourselves).

**Comment by ariel-phet** [comment]
@amanda-phet can you give your thoughts on this issue and also perhaps plan to bring it up at the next status meeting?

**Comment by amanda-phet** [comment]
This is a similar issue that we had with YouTube, but again I don't think teachers will go through that kind of trouble to access the video. 

Just for clarification, how could you view the page source when not logged in?

**Comment by amanda-phet** [comment]
I get it- right-click and view page source, then you can find the vimeo URL. Yeah, that is definitely possibly if someone is truly looking for the URL! Again, I don't think this is a serious concern. 

Will there be a public Vimeo page?

**Comment by ariel-phet** [comment]
@amanda-phet and @aaronsamuel137 - another option to consider might be to have some very "generic" sim primer screenshot when you are not logged in. That seems like it would be an easy compromise, and mean we would not need a separate screen shot for each primer, and keep everything nice and private.

**Comment by aaronsamuel137** [comment]
That sounds like a nice solution to me.

**Comment by amanda-phet** [comment]
That's fine. Let's use a generic sim primer screenshot for when you're not logged in. When you are logged in, it will be a thumbnail from the video. 

I will look in to finding a generic screenshot, but for now none of the sims will have a primer so this is low priority.

**Comment by aaronsamuel137** [comment]
I think we have determined that this in no longer necessary. Even though you can access the video URL by viewing the page source, Vimeo privacy settings won't allow you to watch the video unless you are actually on the phet site. For instance, this is the link to the video currently on the area-builder page on phet-dev: https://player.vimeo.com/video/123764106

However, technically there is still a way around this. Someone could actually go in and modify the page source code (in Chrome dev tools for instance) so that the video-blocker is no longer over the video, and then watch the video while not logged in. Not sure if we care.

**Comment by amanda-phet** [comment]
I agree- this is resolved. Closing.
