### ISSUE TITLE
Add column to user table for "trusted translator"

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#119]

**Comment by aaronsamuel137** [comment]
I've added this column to phet-dev. Assigning to @oliver-phet to review the admin interface for adding a trusted translator. To mark a user as a trusted translator, you just need to look them up by email and check the "trusted translator" box.

If it looks good, I'll make this change on figaro too.

**Comment by oliver-phet** [comment]
This looks good to me @aaronsamuel137. 

One slightly related question I have - in the past I've noticed an issue where if the email address is not entered with correct capitalization, it will not find the user. (I tried entering "H.alhadlaq@gmail.com" instead of "h.alhadlaq@gmail.com" and the website gives an error. Is it possible to not require proper capitalization for user emails?

**Comment by aaronsamuel137** [comment]
I ran into this issue once too and found it very annoying. I'll look into a solution.

**Comment by aaronsamuel137** [comment]
I'm going to close this issue and track the email issue in another issue.
