### ISSUE TITLE
Colon appears before "Support PhET" on 3 translated home pages.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/website#127]
Tested on 10.9.4, Chrome 41
The following pages have the Colon before "Support PhET". 
http://phet-dev.colorado.edu/fa/
http://phet-dev.colorado.edu/ar_SA/
http://phet-dev.colorado.edu/ku/
That is, it appears as
![screen shot 2015-04-16 at 11 18 53 am](https://cloud.githubusercontent.com/assets/5631059/7187041/348129e4-e42b-11e4-958a-f018734b3f4e.png)
On the english page and all others
![screen shot 2015-04-16 at 11 27 06 am](https://cloud.githubusercontent.com/assets/5631059/7187085/831ea144-e42b-11e4-8518-aefdc61bce55.png)

**Comment by phet-steele** [comment]
@orejolaphet this is because these languages are read from right to left, but I do agree it looks strange. @aaronsamuel137 I do believe there might be a way to move the colon to the other side? From what I've read about RTL languages it seems like in some cases the colon being to the right of PhET is okay. But if all else fails what if we move the "Donate Today" button to the left of the words or something?

**Comment by aaronsamuel137** [comment]
I'm inclined to ignore this - it will go away when the page is properly translated. This is just what happens when an english string with a colon is rendered in a rtl page. There could be work arounds, but it would be a little clunky.

@ariel-phet - let me know if you'd like me to fix this or not.

**Comment by ariel-phet** [comment]
@orejolaphet and @phet-steele - great attention to detail, however, I think @aaronsamuel137 has the correct approach in this case - allow translators to fix the oddness. Although it looks funny, only someone viewing the site in these locales will see it that way (and they likely do not speak english, so it will have little meaning until translated)
