### ISSUE TITLE
'University of Colorado' logo changes

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#132]
Smaller, aligned, greyscale

Currently on phet-dev, the logo is horizontally oriented. We want to keep that logo, but would like a smaller version. The logo also needs to be aligned properly so that when the window is at 768 horizontal pixels, the logo and Sign In/Register buttons are fully visible and right aligned.

Here are screenshots at 768 horizontal:
Mockup:
![screen shot 2015-04-21 at 11 28 59 am](https://cloud.githubusercontent.com/assets/7852916/7258429/b62e8bd4-e819-11e4-8d79-218ad2817b7e.png)

Current:
![screen shot 2015-04-21 at 11 07 18 am](https://cloud.githubusercontent.com/assets/5090275/7258302/e358d80e-e818-11e4-8b39-82e592d4c960.png)

Old:
![screen shot 2015-04-21 at 11 07 41 am](https://cloud.githubusercontent.com/assets/5090275/7258303/e5779e18-e818-11e4-9aa0-97161b3288fe.png)

**Comment by ariel-phet** [comment]
@aaronsamuel137 - since this is one of the final "pixel polishes" and it was important to @kathy-phet to have the CU logo not compete too strongly with PhET logo it would be good to do before we deploy (as we are waiting on the activity licensing info). 

You will also notice in the mockup above that the black and white version of the "CU" is being used. 
@amanda-phet can get you this image but it is also available here:

http://www.colorado.edu/brand/downloads

And officially described here (see the greyscale one on the right hand side)
http://www.colorado.edu/brand/logo/logo-variations

**Comment by aaronsamuel137** [comment]
Sounds good - I can work on this tomorrow. @amanda-phet - will send me the correct logo? It seems easier than filling out that form that CU asks you to fill out.

**Comment by aaronsamuel137** [comment]
I've updated the CU logo. Assigning to @ariel-phet for review.

**Comment by amanda-phet** [comment]
The svg logo looks great. Closing.
