### ISSUE TITLE
Latest sims not on phet-dev

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#144]
We noticed that Molecule Shapes (HTML5), Molecule Shapes Basics (HTML5), and Least-Squares Regression (HTML5) are currently not listed anywhere on phet-dev. 

Is this because when you last pushed phet-dev, they weren't yet published? Will they be there the next time you push to phet-dev?

**Comment by aaronsamuel137** [comment]
They should show up next deploy, once I merge in master. LSR regression might not show up since it is HTML5 only and there were some database changes to figaro that won't propagate over automatically. I can manually do on phet-dev if you think it's important, but once the new sim pages are deployed the two sites will be back in sync anyway.

**Comment by amanda-phet** [comment]
I don't think it needs to manually be added on phet-dev, we were just wondering why we didn't see the latest sims. Thanks!
