### ISSUE TITLE
Confusion with University option when registering

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#168]
When clicking the university option for grades, year 1 year 2+ and graduate are all checked at the same time. I believe this is somewhat confusing; the options for selecting university should all initially be blank. 

There should only be one option to select rather than all three automatically selected for this will cause 
confusion for the users

![screen shot 2015-05-12 at 10 01 28 am](https://cloud.githubusercontent.com/assets/7717368/7591935/ea49b27a-f88d-11e4-8ced-d6916d65daf7.png)

**Comment by aaronsamuel137** [comment]
I agree - does this sound good to you @amanda-phet @ariel-phet?

**Comment by amanda-phet** [comment]
The other grade levels auto-check, so I'm not convinced yet that we'd want a different behavior just for University. Can't a professor teach all three levels?

**Comment by bryo5363** [comment]
@amanda-phet  this is a good point; I just thought it would be confusing for college students registering for the site.

**Comment by amanda-phet** [comment]
In general we probably have fewer students than teachers who register, so my instinct is to favor the needs of teachers a bit more. I think @ariel-phet and @kathy-phet should weigh in, though.

**Comment by phet-steele** [comment]
Can't we make it conditional, where if the user had clicked "Student" versus "Teacher" in the I am a... section, then the behavior of the auto-check is different? If I say I'm a teacher, then have everything auto-checked. If I say I'm a student, don't have everything auto-checked.

**Comment by ariel-phet** [comment]
@amanda-phet & @aaronsamuel137 - I think this question can wait until after deployment, I am sure we will refine this page slightly, but the behavior seems acceptable at the moment

@bryo5363 and @phet-steele - good suggestions, we will look at them after the initial deploy

**Comment by ariel-phet** [comment]
Oh and I think @phet-steele had a good suggestion about the conditional, for a student, we probably only care about their general level.

**Comment by aaronsamuel137** [comment]
Has a decision been made about the exact behavior we want here? Assigning to @ariel-phet to specify and prioritize or close the issue.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - I think the best behavior would be to follow the conditional you have already written for how these levels work when you have a non-US country.

Basically if you check the "Teacher" option you get the expanded checklist with specific grades. If the teacher option is not checked (Student, Researcher...etc), you only see the general levels but with no grade breakdown. And of course if you check the Teacher option but are in a different country you still only get the general levels.

I would say priority is low to medium.

**Comment by aaronsamuel137** [comment]
Seems like a good task for @zepumph. Let me know if you have questions.

**Comment by zepumph** [comment]
Now the extra grades will not show up unless you are in the USA, and the 'Teacher' checkbox is checked. Assigning to @aaronsamuel137 to take a look.

**Comment by aaronsamuel137** [comment]
Seems to be working well. One thing I forgot to mention clearly - js files are aggressively cached so that changes could be cached in varnish or in some intermediary cache that we have no control over (the same is true for css). Therefore, whenever we make changes to js or css files we'll need to bump their version number.

In this case, you'll need to change the name of register-page.js to register-page-v1.js, or something like that.

**Comment by aaronsamuel137** [comment]
Assigning to @zepumph

**Comment by aaronsamuel137** [comment]
Looks like you changed the file name, but not the reference to it in the code. See line 106 in RegisterPanel.html:

```html
<script type="text/javascript" src="/js/register-page.js"></script>
```

Also, the was a major reformatting done in your commit above in phetpage-v10.css. I am in favor of reformatting all of our html and css to use 2 spaces for indents to be consistent with our current github code, but it is better practice to do reformatting changes in separate commit. Not a big deal, just something to think about in the future. I reference issue #123 when doing reformatting commits.

For now I'd say to always assign issues back to me and I'll review and close them, instead of just closing them yourself.

**Comment by zepumph** [comment]
Sorry about just closing it, I refactored looking through comments and strings, but I guess it didn't pick it up. I'll go through and fix it.

**Comment by zepumph** [comment]
I think that should do it, thoughts @aaronsamuel137?

**Comment by aaronsamuel137** [comment]
Looks great, thanks! Closing

**Comment by aaronsamuel137** [comment]
Actually I'll leave this open until it is deployed and reviewed. I'll let @ariel-phet know when it is deployed.

**Comment by aaronsamuel137** [comment]
Assigning to @ariel-phet for review

**Comment by ariel-phet** [comment]
Looks good, closing!
