### ISSUE TITLE
Activity Error 404

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#169]
I uploaded an activity to Color Vision (HTML5), then trying to access it (clicking on the pdf link) I get an error 404, "The requested URL /files/activities/4052/thermo_hw1.pdf was not found on this server."

Mac OSX 10.10.1, Chrome 42.

**Comment by orejolaphet** [comment]
I too have noticed this issue on OSX 10.10.2 Chrome 42

**Comment by amanda-phet** [comment]
I also noticed this on OSX 10.10.2 Firefox 37.0.1

**Comment by aaronsamuel137** [comment]
I think this is an issue that will only affect phet-dev. Still, it would be good to discuss with @jonathanolson at some point so we can have this working on phet-dev like it would on figaro.

**Comment by jonathanolson** [comment]
Did anything show up in the error logs when the upload was attempted?

**Comment by phet-steele** [comment]
Do you mean the upload of when I browsed through my computer and selected the pdf, or when I tried to access the file from the activity page as is this issue?

**Comment by aaronsamuel137** [comment]
The upload actually works fine. However the url that shows up is "phet.colorado.edu/file/activities/XXXX" even on phet-dev. This url seems to be coming from a WebsiteProperties file, but I can't figure out where the properties are actually coming from.

Also, both "phet.colorado.edu/file/activities/XXXX" and "phet-dev.colorado.edu/file/activities/XXXX" appear to redirect to phet-downloads.edu, which seems to point to figaro. So even though the file is uploaded correctly on phet-dev, there is no way to get to it since it redirects to figaro.

**Comment by jonathanolson** [comment]
Maybe in context.xml:
```
<Parameter name="phet-download-location" value="http://phet.colorado.edu/files" override="true"/>
```
?

**Comment by aaronsamuel137** [comment]
I've fixed this issue on phet-dev. To be clear, this wouldn't have been an issue on the main site - it had to do with setting on simian and not with the actual website code.

In fact, we'll have to make a note to change these back if we ever start running phet.colorado.edu off of simian.

**Comment by aaronsamuel137** [comment]
Is this working for you now @phet-steele? Feel free to close if so.

**Comment by phet-steele** [comment]
It's good!
