### ISSUE TITLE
Clicking videos about PhET links to full screen video

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#174]
I am not sure if this was intentional or not but clicking the video links in the About PhET main page will take the user to a full screen video rather than keeping the user on the page.

Personally I think this is distracting for the user; the user should not be diverted from the PhET page; these videos can be accessed via the YouTube links on the side. If the videos rather played on the same page, or were linked to a different page on the website I believe this would be much more accessible for the user.

**Comment by bryo5363** [comment]
Instead of linking to the full screen, the videos should appear where the " What is PhET? A short introduction to the PhET simulations" video appears. 

![screen shot 2015-05-12 at 11 13 44 am](https://cloud.githubusercontent.com/assets/7717368/7593521/12b8cdf4-f898-11e4-88df-5dddd8c4b14a.png)

**Comment by ariel-phet** [comment]
@amanda-phet - I think this question can be your call

**Comment by amanda-phet** [comment]
Having the videos open up a full-screen page does seem unnecessary. However, I am inclined to ignore this for now since this is a page that we did not touch in the sim-page redesign. I will add it to our list of future site improvements.

**Comment by amanda-phet** [comment]
This does not seem to be an issue anymore. In the past week it seems that videos no longer open full-screen and instead open in a custom popup:
<img width="1090" alt="screen shot 2016-07-05 at 1 17 31 pm" src="https://cloud.githubusercontent.com/assets/7852916/16596826/de3738ac-42b2-11e6-90cb-e1f1ed2ab69c.png">

While we probably want to come up with a new design, this issue is no longer relevant. Closing.
