### ISSUE TITLE
Why are there two links to HTML5 sims?

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#182]
I noticed on the front page that there are two links to the HTML5 sims; in fact these links are right next to each other. 

![screen shot 2015-05-13 at 9 53 21 am](https://cloud.githubusercontent.com/assets/7717368/7614731/f323d114-f955-11e4-9b48-7a98df51461f.png)

**Comment by amanda-phet** [comment]
We are planning to "wean" users off of accessing HTML5 sims from that location. Eventually the button will be gone, and then the logo.

**Comment by ariel-phet** [comment]
Hey @bryo5363 - the idea is that we eventually want to migrate away from this link, since now we are going to be forefronting the HTML5 sims with the new HTML5 sim pages.

In this case, we wanted something that was clearly clickable (the "HTML5 SIMS" button) and the HTML5 logo for the eye-catching factor. I agree it is slightly odd that they feel like to separate clickable links, we plan to get rid of this banner entirely when we redo the navigation.
