### ISSUE TITLE
Language switch while editing a profile

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#198]
Similar to #188, if you sign in then go to edit your profile and switch the language while on the profile page, you'll go back to your first language after clicking update.

Tested on Win 8.1 browsers

**Comment by bryo5363** [comment]
observed on OSX as well

**Comment by aaronsamuel137** [comment]
Once you edit your profile you are redirected back to the page you were on before going to the edit profile page. I'm inclined to leave this behavior as it is.

Assigning to @ariel-phet to either close or assign back to me.

**Comment by ariel-phet** [comment]
I think I am with you @aaronsamuel137 - it seems like an odd use case to choose a new locale while on the edit profile page instead of beforehand. Even so, if someone does actually follow this scenario, they will be able to easily switch locale again when returned to the original page. Perhaps a minor inconvenience, but will only happen in this very specific use case. I am OK with leaving as is, closing.
