### ISSUE TITLE
bookmark to HTML5 sims no longer works

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/website#216]
I had a bookmark to http://phet.colorado.edu/en/simulations/category/html, for quickly getting to the HTML5 sims on the PhET website.  After the website upgrade, that URL no longer works.  Figured I'd mention it in case it was an oversight.

**Comment by pixelzoom** [comment]
Is the "New" category now equivalent to "all HTML5 sims", or will this category be just the most recent HTML5 sims.  I'm looking for an equivalent link that will show all HTML5 sims published on the PhET website.

**Comment by aaronsamuel137** [comment]
Yes, "new" is equivalent to all html5 sim at this point. As of now it is expected that category/html will not work.

However, the figaro logs get a lot of messages indicating that people are trying to access category/html, so perhaps we should make this go to the same page as category/new. What do you think @ariel-phet?

**Comment by pixelzoom** [comment]
PhET policy in the past has been to put in redirect, rather than orphaning URLs.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - yes we should put in redirects. Many people will have bookmarked "category/html"

**Comment by ariel-phet** [comment]
@pixelzoom for the forseeable future this will be only HTML 5 sims

http://phet.colorado.edu/en/simulations/category/by-device/ipad-tablet

@aaronsamuel137 - I think the longterm goal is to have "new sims" really be the latest sims, but for at least the next year or so having the "HTML5" link going to the new sims is the correct behavior.

**Comment by pixelzoom** [comment]
@ariel-phet wrote:
> @pixelzoom for the forseeable future this will be only HTML 5 sims

But it will not be the complete set of HTML5 sims. I doubt that we plan to show all HTML5 sims in the "New" category several years from now.  So I guess the answer to my question is "no, there will not be a link to all published HTML5 sims".

**Comment by ariel-phet** [comment]
@pixelzoom - yes the link I shared will be exactly what you are looking for since it is the "iPad" category and only HTML5 sims run on iPad

**Comment by pixelzoom** [comment]
Awesome, thanks.

**Comment by aaronsamuel137** [comment]
Should we redirect to http://phet.colorado.edu/en/simulations/category/by-device/ipad-tablet or to http://phet.colorado.edu/en/simulations/category/new?

**Comment by ariel-phet** [comment]
Hey Aaron, for the moment redirect the HTML sims link to "category/new" - when we fix the nav on the site the plan is to remove the "HTML Sims" button. We may well make an "HTML5" category for sims at some point, but all that is TBD. At some point (probably a year from now) we will have the "new sims" really just be the latest sims. But before we did the recent changes to the website, our "new sims" category was stagnant for two years...(and all Java sims!). So I think we can have all HTML5 sims populate the new sims category safely for awhile since we want to promote all these sims for the time being. 

@pixelzoom is correct - that is not a long term solution and will eventually change to reflect only the most recent sims, but again, probably at least a year out before we change that.

**Comment by aaronsamuel137** [comment]
Redirect added. Closing
