### ISSUE TITLE
Design of Change Password page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#219]
The Change Email Address page looks like our newer forms with the entry boxes and button. Can we do the same to the Change Password page? 

Current appearance and Desired appearance:
![screen shot 2015-06-02 at 4 30 43 pm](https://cloud.githubusercontent.com/assets/7852916/7948800/b4847c98-0944-11e5-980e-a3dc4153592d.png)

**Comment by aaronsamuel137** [comment]
Do you want to take a shot at this @zepumph? I can point you in the direction of some relevant css classes.

**Comment by zepumph** [comment]
@aaronsamuel137  I pushed it to change-email this morning, so take a look when you get a change. You may still see colons, because I manually changed them in the admin tools, but I also put them in stringChanges, so keep me posted.

**Comment by aaronsamuel137** [comment]
Looks like an accidental import of:

```java
import com.navnorth.learningregistry.util.StringUtil;
```

in StringChanges.java

**Comment by aaronsamuel137** [comment]
Also, you'll need to use overwriteString() instead of addString() in String changes. You can see the colons are still present on phet-dev. overwriteString takes the current string value and the new string value as arguments. addString does nothing if there is already a string with that key, even if you are trying to add a different value.

You'll want to overwrite the string for the submit button to "Change Password" too (changePassword.submit).

**Comment by aaronsamuel137** [comment]
Assigning to @amanda-phet to review. This is currently only on phet-dev, and will be deployed with the new change email work.

**Comment by amanda-phet** [comment]
It looks good to me. I'm not sure it's necessary to duplicate the labels for each entry box, but it certainly is clear. 

Not sure if I should close the issue or not, so feel free to close it when you prefer.

**Comment by aaronsamuel137** [comment]
Closing the issue. This won't go live on the main site until the change email changes do, since they are on the same branch.
