### ISSUE TITLE
Add 'Linux' as a category to Troubleshooting

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#222]
Can we add a troubleshooting page (and navigation link) for 'Linux'?

The new page will have a single issue (at least for now):
> The offline installer doesn't appear to be working or I get a "segmentation error" when I attempt to open the 'PhET_linux_installer.bin' file via terminal.

1. Open the console/terminal.
2. Navigate to the folder where the download is.
3. Run the following two commands:
    1. chmod 777 PhET-Installer_linux.bin
        1. This will give your system permissions to execute the file.
    2. --mode text ./PhET-Installer_linux.bin
        1. This does the install.
        2. Some systems may require "sudo" but first try without.
4. Choose the install directory.
    1. Choose carefully because after the install you cannot move the
       folder as many of the links will break as they use absolute and
       not relative referencing.

**Comment by oliver-phet** [comment]
@arnabp Can you do a run through of the steps above to double-check for accuracy before assigning to the web team?

**Comment by zepumph** [comment]
@arnabp will you use #96 from here, because this is pretty much a repeat. A version of this page is on phet-dev. see: https://phet-dev.colorado.edu/en/troubleshooting/linux
I didn't see this issue when I added the page, but for now I'm closing this and assigning #96 to @arnabp to run through the linux steps. Sorry for any confusion on my part.
