### ISSUE TITLE
New 404 error page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#282]
Mariah designed a new image for our "error: page not found" page. This might be a fun thing for Matt to work on as an initial project. 

See https://github.com/phetsims/tasks/issues/319 for more details.

**Comment by aaronsamuel137** [comment]
Commit: 02507b774172c0b5f8c1965f7bcf5e55c037a67f

**Comment by aaronsamuel137** [comment]
@mattpen and I worked on this. Take a look on phet-dev and let me know how it looks to you @amanda-phet.

**Comment by ariel-phet** [comment]
@aaronsamuel137 @mattpen I think this is looking good! Out of curiosity, I think one pretty fun improvement (but not a priority at all) would be do have a sign post with different directions such as the example below (but labels like "sims" "math" or such)

If we had Mariah draw that up, would it be touch to make certain regions clickable, so that if you clicked on "sims" say, it would take you to the main sim page?

![road-signs_pierce-column2](https://cloud.githubusercontent.com/assets/4051174/10501394/282dd906-729e-11e5-8fca-50d1991e144a.jpg)

**Comment by mattpen** [comment]
@ariel-phet This should be relatively easy to accomplish with an HTML image map.  If Mariah sends me an image I can add links to it.

**Comment by ariel-phet** [comment]
@mattpen sounds good...won't be done soon, but we will keep it in mind, what you have up now is a nice improvement!

**Comment by amanda-phet** [comment]
This looks great to me!

**Comment by ariel-phet** [comment]
self-assigning to work with Mariah on the road sign idea at some point.

**Comment by ariel-phet** [comment]
@mattpen feel free to push the current version to the main website!

**Comment by aaronsamuel137** [comment]
Deployed. Unassigning for now since it doesn't seem like the sign suggestion will be implemented soon.

**Comment by ariel-phet** [comment]
I think I am just going to go ahead and close this issue. Bigger fish to fry.
