### ISSUE TITLE
Change section on Our Team page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#295]
Ariel suggested that we change "Undergraduate Assistants" to "Student Assistants" since we will want to add Matt to the Our Team page.

**Comment by aaronsamuel137** [comment]
I've updated this string. Actually, it was in the AdminEditContent section, but the team page was mislabelled licensing due to a copy paste error, which is probably why you didn't see it. This labelling error will be fixed on the next deploy.

Feel free to add Matt whenever. I guess the next step is to get a black and white headshot for him?

**Comment by amanda-phet** [comment]
Thank you!
