### ISSUE TITLE
CCK Donation Ask

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#313]
@mattpen this will be a high priority project for you and will trump most other work (except critical fixes) in terms of priority

Originally, we had thought about putting this "ask" within the sim itself, but we have decided to try it out directly on the website itself. Details on the look of the ask are here:

https://github.com/phetsims/tasks/issues/395

The basic behavior should go something like this:
1. If you go to the sim page for Circuit Construction Kit (CCK) or one of its variants the ask does not yet appear.
2. If you click on the sim screenshot (run) or the download button the ask dialog appears and follows a similar paradigm to the sign in dialog (the dialog is bright, website behind dims)
3. If you click "maybe later" the action you had previously chosen occurs (downloading or running the sim).
4. If you click "donate now" a new browser tab opens with the donation page
5. We will ideally want to build some tracking into this ask so we can know how often people are clicking donate now, and perhaps even have a cookie so that the ask does not appear if they have already donated in the past ( @jonathanolson will obviously help with this)

**Comment by ariel-phet** [comment]
@jonathanolson please make a list of bullet points as to why dealing with the "direct link" to the jnlp would be problematic.

**Comment by ariel-phet** [comment]
@jonathanolson and then reassign issue to @mattpen -- thanks!

**Comment by aaronsamuel137** [comment]
@mattpen, talk to me before you start this. There are already ways of handling dialogs like this in the website code, so I can save you a lot of time showing you how the previous ask dialog was set up.

**Comment by ariel-phet** [comment]
Thanks @aaronsamuel137!

**Comment by ariel-phet** [comment]
Artwork avaiable in this folder (cckask2.ai)

https://drive.google.com/drive/folders/0B-YvjkIIcS_aRVFvZ2NDYlZ6Qkk

**Comment by kathy-phet** [comment]
Just to give some data on how the number of asks will change by taking this website based approach: 
GA has number of hits to the CCK simulation pages (all flavors) in April 2015 as: 316,000
Yotta shows the number of .jnlp runs for CCK simulations (all flavors) in April 2015 as: 1,225,787 

So assuming that when someone lands on CCK simulation page, they do actually try to run the sim in some way, we will only get about 25% of the sim runs -- missing about 3 out of 4 simulation launches.

**Comment by ariel-phet** [comment]
@kathy-phet - however I would say that a numerous percentage of those jnlp launches may well be students (quite likely in fact) so yes, you might be missing asks, but that may not be a bad thing, since the ask is not going in front of students as much.

**Comment by kathy-phet** [comment]
True, that could be. At any rate, we will see what we get. GA says we get about 1,300 landing on the registration page per day right now. About 8,000 landing on CCK page per day right now. M-F at least.

**Comment by jonathanolson** [comment]
> @jonathanolson please make a list of bullet points as to why dealing with the "direct link" to the jnlp would be problematic.

1. When a JNLP is saved and run, it will attempt to download the JNLP location (expecting a JNLP). If this isn't a JNLP file for those users, this will break and the sim won't run. This can be worked around somewhat by trying to detect the user-agent string.
2. If we do detect the user-agent string for ALL Java Web Start versions we'd support (complicated testing procedure for ~3+ versions), Google generally frowns upon changing results based on user-agent.
3. Google would probably see the HTML page, and might derank direct-to-JNLP results.
4. We'd need a consistent way to actually load the JNLP. If this is a different URL (say sim_en.jnlp?actualJNLP), then someone can link THAT, and now they don't see the splash.
5. This detection of the JWS user-agent might not be possible on Apache, AND returning an adaptable (Tomcat-generated) translated splash would mean we couldn't use Apache for this, thus:
6. Tomcat now has to serve all JNLP requests. So more pressure slowing down Tomcat.
7. JNLPs wouldn't be able to be cached for the future, so we couldn't use Varnish for them.
8. Having Tomcat handle ONLY these URLs is also very problematic. We might need to serve the entire /sims/ out of Tomcat instead of Apache, also slowing things down.
9. Overall, it's something that is very error-prone, performance-compromising and will require a ton of testing. Doing something on the website ('click')-side is so much easier.

I'd say even if you want to use the 'direct link' approach, it would be best to START with the website-side approach initially, and test how it does. Then we could see how much time and future maintenance it would be worth to look into the 'direct link' approach.

**Comment by kdessau-PhET** [comment]
Here's the donate now URL for this Ask: https://donatenow.networkforgood.org/html5cckdonatenow

**Comment by kdessau-PhET** [comment]
Changed the donate now URL for this to:  https://donatenow.networkforgood.org/html5donatenow

**Comment by mattpen** [comment]
@ariel-phet When a user clicks the DonateNow button, the page will open in a new tab.  Can you clarify what should happen on the original page after clicking the Donate button?  Options are 1. nothing, the CCKask popup remains 2. Sim launches or prompts to download in the background, 3. The CCKask popup disappears with no other action.

**Comment by mattpen** [comment]
Regarding requirement 5, do we want to skip the ask using tracking with a cookie if the user has simply 
visited the DonateNow link (easy to implement), or actually donated (not so easy)?

**Comment by aaronsamuel137** [comment]
I've reviewed changes so far. Here's a few issues I've noticed:

In sim-page.js:

```js
if ($('meta[property="og:title"]').attr('content').indexOf('Circuit Construction Kit') < 0 )
```

This won't work in a non English locale since the og:title will be translated. Better to use the URL instead, or something else that won't change in different locales.

Also, there are 2 occurrences of `dialogOpened = true;` in sim-page.js. Are these needed? dialogOpened is never declared as a var, and doesn't seem to be used anywhere, just assigned to (at least in sim-page.js).

Another small issue: it is generally considered better practice in Javascript to use === and !== instead of != and == for comparing numbers (and most other things).

Everything else looks good to me, though it might be good to discuss the browser compatibility issues you are running into. I haven't had to use those kind of browser specific if statements before, and am wondering why they are necessary.

Nice work!

**Comment by mattpen** [comment]
This popup is not translatable because the text is part of the image, should it be popping up in a non-english locale?

**Comment by aaronsamuel137** [comment]
>This popup is not translatable because the text is part of the image, should it be popping up in a non-english locale?

Good question, I would think so, but I think @ariel-phet or @kathy-phet should answer this to be sure.

**Comment by mattpen** [comment]
@ariel-phet Can you please send an image without text so we can make the ask translatable?

**Comment by ariel-phet** [comment]
Image sent back to @mattpen

**Comment by mattpen** [comment]
@kathy-phet @ariel-phet After discussing the problem of tracking the number of times a user is asked, @aaronsamuel137 and I determined that it is easier to track this in GA because these links will often be clicked when a user is not logged in.  If the user is not logged in, we currently have no place to store the ask data.  

In addition, do we want to track the specific page where the ask is shown/clicked?  In other words, do we want to be able to tell who is clicking the CCKAsk link in the DC vs AC version?

**Comment by kathy-phet** [comment]
Hi Matt, I agree - track even if not logged in so GA seems like the best approach. I don't need to know the page from which the CCKAsk was launched - just the total number viewed. Thx!

**Comment by mattpen** [comment]
Excellent, thanks Kathy.  I'll make the strings translatable on Monday and push it to phet-dev to test.

**Comment by mattpen** [comment]
@kathy-phet @ariel-phet , the cckAsk dialog box is now up on **[phet-dev](https://phet-dev.colorado.edu/en/simulation/circuit-construction-kit-dc)**.  Let me know if you see anything that needs to be improved.

**Comment by phet-steele** [comment]
The text at the top looks decent on IE11, but not FF or Chrome (Win 8.1). All of them have the text slightly too high compared to the nearby colon.
IE11:
![ie ed](https://cloud.githubusercontent.com/assets/5863899/11482084/156b2afa-975e-11e5-9b0e-38524533311a.PNG)

FF:
![ff ed](https://cloud.githubusercontent.com/assets/5863899/11482091/1f8fedcc-975e-11e5-9246-e4d6261baa78.PNG)

Chrome:
![chrome ed](https://cloud.githubusercontent.com/assets/5863899/11482105/2b430b04-975e-11e5-9f61-990c7973da68.PNG)

The pointer/yardstick or whatever it is looks fine on FF, but gets real close to the text on IE11 and Chrome:

FF:
![good stick](https://cloud.githubusercontent.com/assets/5863899/11482183/a62eb232-975e-11e5-95b7-27dbe32f36cb.PNG)


IE11 & Chrome:
![bad stick](https://cloud.githubusercontent.com/assets/5863899/11482172/9676a110-975e-11e5-9903-3e9033ebf2be.PNG)

**Comment by mattpen** [comment]
I put the translatable strings under the "Simulation" section of the website utility.  If they should be somewhere else, please let me know.

**Comment by kathy-phet** [comment]
For the yellow button - looks like you can just move the whole button up a tad.

**Comment by mattpen** [comment]
@ariel-phet - is it possible to get an image without text where the yellow button does not overlap the yardstick?

**Comment by kathy-phet** [comment]
Two suggestions: 

It looks like making the whole scene just slightly wider, so the black board could be wider would help keep the text legible and within the blackboard. 

Also, is there a way for the FF text to be less pixelated? 

But overall -  its looking great and exciting to see it close! 
K

**Comment by ariel-phet** [comment]
@mattpen pretty much anything possible...are you available on skype at some point for pixel polishing?

**Comment by mattpen** [comment]
@ariel-phet I'm available until 3PM today

**Comment by kdessau-PhET** [comment]
Also FYI, I've requested the CCK donation page to be updated to match the website. It will take up to 10 days for complete.

**Comment by mattpen** [comment]
@kathy-phet @ariel-phet I've polished up the appearance and pushed the changes to phet-dev.  Please let me know what you think.

**Comment by ariel-phet** [comment]
Looking pretty good to me!

**Comment by kdessau-PhET** [comment]
Looks good to me too!

**Comment by kathy-phet** [comment]
Looks good to me too! I don't think we need to wait until Network for Good look is updated. It will be nice when it is, but it doesn't seem like a show stopper to me. 

Thanks, Matt! Nice work everyone!

**Comment by mattpen** [comment]
Thanks everyone.  I'll push this to the main site one evening this week.

**Comment by kathy-phet** [comment]
Hi Matt, Just wondering what day you might expect this to get posted. It would be great to see it up on the main site and start seeing how effective it is. Thanks! K

**Comment by mattpen** [comment]
Hi Kathy, I plan on publishing it later tonight.

**Comment by kathy-phet** [comment]
Great. Thanks!

**Comment by mattpen** [comment]
This is now published to the main site.  There appears to be an error in the logic for the GA code which I'm sorting out now.

**Comment by mattpen** [comment]
Ok, I think I've sorted out the GA behavior.  You can find it in GA under Event Category = Donation and Aciton = CCKAskShow (meaning the popup was displayed) and Action = CCKAskClickDonate (meaning they went to the network for good site).  If that's not clear please let me know.

**Comment by kathy-phet** [comment]
Thanks, Matt!

**Comment by kathy-phet** [comment]
Hi Matt, 
The GA tag seems to not be working properly. Under CCKAskShow it shows over 400,000 since Friday, but when I look at the source URLs associated with the Ask it lists all the individual sim pages (not just CCK). It is quite a bit different than if I look at the tag that is "Ask" right now (which is really the RegistrationAsk). The CCKAskClickDonate seems more reasonable at 500 since Friday.

You can look at this information at GA going to "Behavior" and then "Events" then "Top Events" then "Donation". 

@jonathanolson might be able to help look at the GA code if you want another pair of eyes on that. 

![image](https://cloud.githubusercontent.com/assets/5096804/11665704/ffccb198-9da5-11e5-921b-434921ecbce9.png)

**Comment by mattpen** [comment]
Kathy,
The fix I applied didn't appear because the old javascript file was cached in varnish.  Yesterday, Jonathon helped me figure out how to force the file to update.  I'm testing it out on phet-dev today and I will push the changes to the main site tomorrow night.

**Comment by kathy-phet** [comment]
OK - thanks for the update. K

**Comment by mattpen** [comment]
Kathy,  the javascript on figaro should have the correct logic for GA now. In the next day or so, we should stop seeing CCKAskShow events from non-CCK pages.

FWIW, I did a search on the source URL's for "circuit-construction-kit" for the CCKAskShow event since 12/3.  It shows approx 49,000 total and 23,000 unique events.  These numbers are slightly less than the total Run and Download events for circuit-construction-kit, so I'm assuming they are correct.

**Comment by kathy-phet** [comment]
Thx!

Sent from my iPhone

On Dec 9, 2015, at 8:58 PM, Matt Pennington <notifications@github.com<mailto:notifications@github.com>> wrote:


Kathy, the javascript on figaro should have the correct logic for GA now. In the next day or so, we should stop seeing CCKAskShow events from non-CCK pages.

FWIW, I did a search on the source URL's for "circuit-construction-kit" for the CCKAskShow event since 12/3. It shows approx 49,000 total and 23,000 unique events. These numbers are slightly less than the total Run and Download events for circuit-construction-kit, so I'm assuming they are correct.

-

**Comment by mattpen** [comment]
The GA metrics have been reporting less than 3 CCKAskShow events/day for non-CCK pages for ~3 weeks.  Closing as it appears to be working correctly.
