### ISSUE TITLE
By device category not displaying correctly for other locales

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#314]
@aaronsamuel137 on the by device category, sims are not showing up properly for non-english locales. For instance, many java versions in the iPad category

I think I see what the problem is. It appears there is some competing website logic. If you are viewing the site in a particular locale, If a translated version exists, it is populating the sim list with that version. So for instance, if balloons and static electricty is translated into german it shows the Java version not the HTML5 version. But the java version does not run on ipad (or chromebook). So we might need a special rule to always show the HTML5 version in these categories (and show the translated HTML5 version if it exists).

I am guessing this is a bit involved, so you probably won't have time to work on it. Feel free to comment and reassign to @mattpen or @jonathanolson (or maybe this a good task for them to pair on?)

**Comment by aaronsamuel137** [comment]
I'll probably have time to do this, and I'll reassign to @mattpen if not. Planning on looking into it next.

**Comment by aaronsamuel137** [comment]
There are other things to think about here too. For instance, http://phet.colorado.edu/da/simulations/category/physics/heat-and-thermodynamics shows the flash version of friction, not the HTML5.

Also, going to the html5 friction sim page (http://phet.colorado.edu/da/simulation/friction) you see a message that the sim is not translated, though it actually is, and the link still links to the English sim.

I am now remembering that there were quite a few things we planned on changing when the translation utility went live, so perhaps we should get a comprehensive list of all the changes that are needed in this regard.

**Comment by ariel-phet** [comment]
@aaronsamuel137 please start making such a list. We can also have someone like @phet-steele go through the site in a different locale and identify inconsistencies we may not have considered.

**Comment by aaronsamuel137** [comment]
- Links in the sim display panel should go to HTML5 pages in translations if there is an HTML5 translation
- Sim page should link to translated sim when it exists
- Related sim section for translations should link to translated sim when it exists
- There might be some other things, we should probably have someone browse through and check that everything looks right.

In general, I think we should remove the special cases for non-english simulation displays. The HTML5 sims should just follow the default behavior here of appearing in the alphabetical list if a translation exists, and otherwise appear with a greyed out title at the bottom. This will solve the by-device issues automatically.

I will deploy a first pass of these changes to phet-dev today, and then we can have someone look through to see if there is anything I missed.

**Comment by ariel-phet** [comment]
Excellent

**Comment by aaronsamuel137** [comment]
OK this is deployed to phet-dev. @ariel-phet can you take a look or assign to someone else?

One other question here. The "Play with sims" button on the home page currently takes you to all sims instead of new sims if you are not browsing in English. Should we change this now that there are some HTML5 translations?

**Comment by aaronsamuel137** [comment]
Has anyone had time to review this? It would be nice to deploy live tonight since this change is on master with some other changes we have made. Not sure who should do it, probably one of @ariel-phet, @amanda-phet, @arouinfar, @phet-steele

**Comment by amanda-phet** [comment]
I looked it over and things looked good to me, but some more people should probably also look!

**Comment by amanda-phet** [comment]
Sorry, looking again and have a question: When browsing All Sims, the non-translated sims should be at the bottom, right? It seems like they are for http://phet-dev.colorado.edu/da/simulations but not for http://phet-dev.colorado.edu/pt/simulations (I'm not sure I even understand the order here... it seems like HTML5 are all at the bottom but java and flash are still sprinkled in there).

**Comment by aaronsamuel137** [comment]
I've looked into this a little bit, and I think I've figured out why it's happening. For one thing, this happens already on phet.colorado.edu. I think the reason is that there actually is a Portuguese translation, it's just Brazilian Portuguese (pt_BR vs pt). The site is smart enough to realize that there is a Portuguese translation for the given sim, so it isn't marked as untranslated (grey text). However, since it is still a different locale, the sim page still says that the sim doesn't exist in the given locale.

So the order is correct in a sense. It is translated alphabetically, and then untranslated alphabetically. All of the Java/Flash sims at the bottom are likewise translated in pt_BR but not pt.

Any thoughts about what to do here? We could mark everything untranslated that doesn't have an exact locale match. Or just leave it as is.

**Comment by amanda-phet** [comment]
Ah, so I just happened to click on a locale that has a unique way to sort!

Otherwise it seemed to look ok to me but maybe some others should take a peek too.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Wed, Nov 18, 2015 at 7:10 PM -0800, "Aaron Davis" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've looked into this a little bit, and I think I've figured out why it's happening. For one thing, this happens already on phet.colorado.edu. I think the reason is that there actually is a Portuguese translation, it's just Brazilian Portuguese (pt_BR vs pt). The site is smart enough to realize that there is a Portuguese translation for the given sim, so it isn't marked as untranslated (grey text). However, since it is still a different locale, the sim page still says that the sim doesn't exist in the given locale.

So the order is correct in a sense. It is translated alphabetically, and then untranslated alphabetically. All of the Java/Flash sims at the bottom are likewise translated in pt_BR but not pt.

Any thoughts about what to do here? We could mark everything untranslated that doesn't have an exact locale match. Or just leave it as is.

-

**Comment by ariel-phet** [comment]
Here is one odd thing I see. If you view the site in danish, and look at the ipad category:
http://phet-dev.colorado.edu/da/simulations/category/by-device/ipad-tablet

Beer's Law Lab shows up at the top of the list but as "Beer's Law Lab" not as the translated name of the sim. Yet, if you open the sim, it opens in the Danish language. Seems odd since all the other translated HTML5 sims show the translated sim title.

**Comment by ariel-phet** [comment]
Otherwise things are generally looking good to me.

**Comment by kathy-phet** [comment]
Seems likely that the website has these two fields - the Java sim name and the html sim name - as different strings so the translator would need to have both strings in the website code translated. In this case the sim is translated but the website string is not yet? Could that explain?
K

Sent from my iPhone

On Nov 18, 2015, at 11:16 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


Otherwise things are generally looking good to me.

-

**Comment by aaronsamuel137** [comment]
This is actually due to the fact that the translator didn't translate the title, and therefore it is defaulting back to English. You can see it here in rosetta: https://phet.colorado.edu/translate/sim/beers-law-lab/da, the field for beers-law-lab.title is not translated. Looks like there are quite a few other fields left untranslated too, not sure why.

**Comment by aaronsamuel137** [comment]
Any thoughts on my question from https://github.com/phetsims/website/issues/314#issuecomment-157829209?

>The "Play with sims" button on the home page currently takes you to all sims instead of new sims if you are not browsing in English. Should we change this now that there are some HTML5 translations?

**Comment by ariel-phet** [comment]
@aaronsamuel137 would it be possible to have some sort of threshold in the locale? For instance, I would feel comfortable sending someone viewing in Brazilian Portuguese to the new sims page, but in a locale that has no translations that might not be so useful.I am not sure if that is worth the additional logic on the website right now...maybe we should make an issue that once we have deployed 20 or so translatable HTML sims we switch this behavior?

**Comment by ariel-phet** [comment]
and @aaronsamuel137 thanks for the beers law lab explanation. Just wanted to make sure it wasn't something anomalous. Overall I would say deploy, and we will have someone like Steele go through and look for any other issues, nothing else was obvious to me.

**Comment by aaronsamuel137** [comment]
>maybe we should make an issue that once we have deployed 20 or so translatable HTML sims we switch this behavior?

Sounds like a good plan. I'll create the issue.

>Overall I would say deploy, and we will have someone like Steele go through and look for any other issues, nothing else was obvious to me.

I'll deploy tonight.

**Comment by aaronsamuel137** [comment]
Deployed. Anything else to do here @ariel-phet?

**Comment by ariel-phet** [comment]
Nope, looking great, thanks!
