### ISSUE TITLE
Help Center translations shoud be "out of date" after a string is edited

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#326]
@mattpen When editing existing questions in the Help Center that have been translated in the past, the translation admin page is supposed to outline the now out of date translations in yellow. Instead they are outlined in red signifying they haven't been translated before. Discovered on 11-16, verified as still not working on 11-20.

**Comment by mattpen** [comment]
@oliver-phet @phet-steele I *think* this issue should be fixed now.  I found a problem where the edit function was just creating a new Translated String every time you edit instead of only when you change the system name.  Can you test it out?  I'll take a look, but I'm not an expert with the translations yet.

**Comment by phet-steele** [comment]
Working for me!
