### ISSUE TITLE
Standardize table format

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#347]
As discussed with @amanda-phet, the tables across the site currently do not have a standard style.  The row heights and font styles should be the same for all tables.  The colors will be dependent on whether the table is sortable (purple) or static (blue).  Sortable tables should have sort-icons appended.  Column widths will not be standard as they depend on the content of each table.

Assigning this to myself.  There are several different feature branches in progress now, this will take some time to accomplish and might be deferred until after the new server is deployed in February.

**Comment by mattpen** [comment]
List of tables that need to be standardized:

- [ ] simulations/sim-name: Teacher-Submitted Activities table
- [ ] simulations/sim-name:  Translations table
- [ ] simulations/translated: main table
- [ ] simulations/translated/locale: main table
- [ ] offline-access: one-at-a-time
- [ ] offline-access: ipad and chromebook
- [ ] for-translators/translation-credits: all tables

**Comment by mattpen** [comment]
@amanda-phet - the following tables are currently not using either of the standard formats.  Should we include any of these in the list above?

- simulation/sim-name: Credits
- simulation/sim-name: Software Requirements
- simulations/translated/locale: untranslated table
- teaching-resources/manage-activities: main table
- for-translators/website

**Comment by amanda-phet** [comment]
I'm not sure what you mean by teaching-resources/manage-activities: main table. Is this the table that lists the activities? If so, it should definitely be added to the list as it already uses the purple table. Or is it the table that allows you to select the sim, type, etc. before clicking browse? If that's the case, do not include it. Either way, we should probably add the table that displays the search results to the list above to be standardized. 

I don't think any of the other tables need to be included, since they are more like lists in my eyes. The for-translator/website table is also not on the main site and looks pretty big.

**Comment by mattpen** [comment]
Sorry I meant the table at https://phet.colorado.edu/en/teaching-resources/manage-activities
Its not currently formatted, should we just leave it in the list style?

**Comment by amanda-phet** [comment]
Thank you for clarifying. I think we can just leave that one as is.

**Comment by mattpen** [comment]
OK, I'm going to go ahead and tackle this one next, using the format agreed upon in #306

**Comment by amanda-phet** [comment]
To make your job a little easier, we are leaning toward just one table at this point instead of two. The universal color for the title row and line separators should be #49597A, the titles should be all-caps and not bold. The only variations should be number of columns, number of columns that have a gray background, and whether or not the columns are sortable. 

Here is a mockup:
<img width="798" alt="screen shot 2016-01-06 at 10 17 55 pm" src="https://cloud.githubusercontent.com/assets/7852916/12162739/364a395a-b4c3-11e5-92f2-8c7e1b8d7ca3.png">

**Comment by mattpen** [comment]
Excellent, thanks.  I'll get started tonight

**Comment by mattpen** [comment]
@amanda-phet - Should the colors of the "Share an Activity!" and "Translate this Sim" buttons change to #49597A also? 

![image](https://cloud.githubusercontent.com/assets/11747676/12227415/82339c2a-b7e9-11e5-8596-8f97d7bef133.png)
![image](https://cloud.githubusercontent.com/assets/11747676/12227418/8f7e11b2-b7e9-11e5-9f9b-4d3fea4fd454.png)

**Comment by mattpen** [comment]
@amanda-phet - I refactored the style for the tables listed above and posted them on phet-dev.  I applied the styles to the tables as they are currently posted on the main site.  If these look good, the next step can be (a) post the new style on the main site, (b) apply the styles to the structural changes from #363, #306, and #324 and post on phet-dev, or both (a) and (b).  The structure and the style are mostly independent in the code now, so either path is easy.

**Comment by amanda-phet** [comment]
These tables look really really nice. The only thing missing right now is the arrow indicator on sortable tables. Without it the tables look too similar and users won't know they can sort. 

> Should the colors of the "Share an Activity!" and "Translate this Sim" buttons change to #49597A also?  

Yes, that is a good idea. I hadn't thought of that. 

>the next step can be (a) post the new style on the main site, (b) apply the styles to the structural changes from #363, #306, and #324 and post on phet-dev, or both (a) and (b).  

What do you think is a good route? I think we need to make the minor adjustment I mentioned above before (a), so for now let's just do (b) so we can see all of the tables. I think that we can do (a) soon, though.

**Comment by mattpen** [comment]
@amanda-phet I automated the arrow indicator so that they will be added to any new sortable table. I also changed the color for the buttons (using #7f90b3 for the hover color).  These changes are now up on phet-dev. 

I've set it up so we can deploy the format to figaro first and then start adding the new table configurations, or we can wait and do it all at once.  Either is easy for me.

**Comment by amanda-phet** [comment]
Looking great!! 

I don't see any reason not to do all of the tables at once. I noticed the change also affects the activity page, but I think it still looks readable.

**Comment by mattpen** [comment]
This was deployed to figaro tonight.  There are still pending changes for the Translated Sims table on the main sim pages and for the Offline Access tables.  They are addressed in other issues, so I'm closing this one.
