### ISSUE TITLE
ar_SA not included in top website translation list to update

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#356]
@kathy-phet Noticed a discrepancy in our website translation numbers. There appear to be 36 website translations (37 including English). 

ar_SA (#9) is not included in the top 'Update a translation table', which is an easy table to use to count translations. It may be nice to have the total number of published website translations available under Administration>Statistics

**Comment by kathy-phet** [comment]
I would actually like to know why ar_SA isn't included in the Table, and go ahead and fix that.

**Comment by oliver-phet** [comment]
I believe the update table was created by @jonathanolson Was there a restriction on the ar_SA translation to not have it updatable?

**Comment by mattpen** [comment]
@oliver-phet - The total count of visible translations will be added to the website as part of #351.

It appears that the actual published translation for ar_SA is the 'parent' rather than a 'child', which is why it is not showing up in the update table list.  English is the only other translation where the parent is published and not a child.  This explains why it is not in the list, but I'm not sure why it would be in this state. I'll keep looking.  

If you look in the full table - translation 9 is published, but I think it should be one of these: 605, 645, 888, 1433, 1439.

**Comment by mattpen** [comment]
@ariel-phet - Can you comment on the priority of this issue?

It's not clear to me if this is a bug or is working as designed.

**Comment by oliver-phet** [comment]
I'm also not sure how this should behave. This translation was setup before I was with PhET.

**Comment by ariel-phet** [comment]
@mattpen if I had to venture a guess I would say that since this is Saudi Arabic it was special at the time...I was not here but we had a large collaboration with King Saud University to get our website and many sims translated into arabic. So for reasons at the time it may have made sense to structure things differently. 

Anyhow, I would say whether it is working as was designed in the past, we should change it now to be on an equal footing to all other locales.

As for priority, I would say good to take care of soonish, I will mark it medium

**Comment by mattpen** [comment]
@oliver-phet - The # of website translations is available in the statistics page and ar_SA is now updatable on the admin page.  @jonathanolson and I fixed it last Friday. Can this be closed?

**Comment by oliver-phet** [comment]
Yep, this looks good. Closing.
