### ISSUE TITLE
Line breaks prevent an ellipsis from appearing

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#369]
@mattpen is aware: Line breaks ("br" tag) prevent an ellipsis from appearing if the break is within the first line of the answer:

![no ellipse](https://cloud.githubusercontent.com/assets/5863899/12340584/f6652860-bad8-11e5-9d5a-5de0a074a142.PNG)

**Comment by mattpen** [comment]
I made an improvement on the current behavior and posted it to phet-dev.  The design was discussed with @oliver-phet  and @phet-steele and deferred to design meeting.

**Comment by mattpen** [comment]
@oliver-phet and @phet-steele - I've encountered a problem when trying to implement the expandable text feature.  Because the text must be translatable and accept html tags but not necessarily have html tags, its extremely difficult to create the one line preview followed by an ellipsis.  There are too many edge cases to create a function that will work in every situation.  

Some potential solutions are:
1. Abandon the 'preview' text, just use the triangle expandable text behavior like on [this page](http://phet-dev.colorado.edu/en/for-translators/translation-credits)
2. Shift the responsibility to the editor and translator.  We would need to either require that all text is wrapped in a structural element (h1, h2, p, span, etc.).  This seems like a liability for the translators.
3. Abandon the use of html tags in the answers. 
4. Make the preview string a separate string from the answer instead of one determined dynamically.

Otherwise, I'll have to write a script to parse out the text and make a preview, which would take a significant amount of time.  Option 1 is probably the easiest to implement.

Also, I noticed that styling elements were added to the Question titles.  You should be aware that these styles would no longer reflect the site-wide style should we decide to make a global change.  Use of <h1>, <h2> alone is preferred over adding the <font color="***"> tags.  Question titles are automatically formatted as <h3>, if you want the larger blue title over the plain black bold style, I can change it to <h2>.

**Comment by phet-steele** [comment]
@mattpen those Question titles were just me experimenting, not necessarily what's going to happen.

**Comment by mattpen** [comment]
@phet-steele In #288 we decided to replace all of the toggle behavior with the triangles.  Closing this issue.
