### ISSUE TITLE
Add download button back for Balloons and Static Electricity

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/website#392]
Balloons and Static Electricity 1.1.0 has been deployed, and the download button should be added back.  It was removed since the download file on 1.0.0 was broken.  I am unfamiliar with the website, would you mind helping with this @mattpen?

**Comment by mattpen** [comment]
@jessegreenberg - I readded the link on phet-dev.  Can you please test and reassign to me afterwards?

**Comment by jessegreenberg** [comment]
Thanks @mattpen, the download for balloons-and-static-electricity is working on phet-dev.  But it looks like balloons-and-static-electricity is missing from the list of HTML5 sims on phet-dev.

**Comment by mattpen** [comment]
@jessegreenberg - The entire HTML5 category page is missing because I just synced the DB with figaro, this is related to another change that will be deployed tonight.  BASE will not show up on the New Sims page because of its publication date, but once I re-add the HTML5 category it will appear there.

**Comment by jessegreenberg** [comment]
I see, thanks for clarifying @mattpen!

**Comment by mattpen** [comment]
This was deployed to figaro tonight.
