### ISSUE TITLE
Font awesome css directory

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#404]
Discovered with consequences reported in https://github.com/phetsims/installer-builder/issues/12. The the reference for font awesome that the website uses is "/font-awesome-4.4.0/css/font-awesome.min.css" which is different than the reference the site uses here: "/css/phet-v49-min.css". This is causing any font awesome icons to be filtered out of the installer since it is not included in the css directory. @mattpen couldn't the reference be "/css/font-awesome-4.4.0/font-awesome.min.css"?

**Comment by mattpen** [comment]
@phet-steele There is more to that directory than just a CSS file, so it doesn't seem like it belongs in the CSS directory.  Why wouldn't the entire Font awesome directory be included in the installer? I think if you move the CSS over we're still going to be missing the Font files.

**Comment by phet-steele** [comment]
tagging @jbphet

**Comment by jbphet** [comment]
The installer builder is explicitly told which directories to package up into the installers, and the font-awesome directory isn't currently on the list, but can be added.  Since it was a CSS file that was missing, I wanted to check to make sure that there was some good reason that it wasn't in the same directory with the rest of the CSS files.  @mattpen - you said, "There is more to that directory than just a CSS file[.]"  Can you be more specific about what all is there?

**Comment by mattpen** [comment]
There are 4 sub-directories with configuration files that are needed for the font-awesome tags to work.  This is a third party package and I'm not familiar with the inner structure or what the effects of changing the directory for the css file would be.  The files can be seen [here](https://github.com/phetsims/website/tree/master/root/font-awesome-4.4.0)  It's not very large - total size of the directory is ~1MB.

**Comment by jbphet** [comment]
Okay, I'll look into adding the directory to the rip.

**Comment by jbphet** [comment]
I've added the directory to those that are packaged into the installer, this should be verified during the next installer test.  Assigning to @phet-steele.

**Comment by phet-steele** [comment]
The awesome font awesome fonts are there! (3/20 build)
