### ISSUE TITLE
Addition of New Teacher PD Videos

### ISSUE THREAD

**Issue by emily-phet** [phetsims/website#456]
There is a new suite of videos - designed specifically for middle school teachers - that will soon be completed. These will need to find a home on the PhET website, in the Teacher Resources area. @schasteen will be the contact for the videos. Is there someone she should be working with to figure out how they can best be incorporated into the existing Teacher Resources structure?

Also, there is a single Chemistry PD video that never found its way onto the site. If this can be added in also, that would be great.

**Comment by ariel-phet** [comment]
@emily-phet is there a timeline by which these videos need to appear after completion?

**Comment by emily-phet** [comment]
@ariel-phet - ideally they would be up in early August, allowing for folks a chance to find them as they prep for the school year. Also, we're not expecting anything fancy. As long as they are findable and it's obvious they are a suite of videos (some of the videos directly reference others in the same suite), that will probably be plenty good enough.

**Comment by ariel-phet** [comment]
@schasteen please contact me when these are ready.

As for the Chemistry PD video I think we are going to find a way to feature this video.

**Comment by schasteen** [comment]
The videos are up, in a single playlist at https://www.youtube.com/playlist?list=PLU4AnY00Zrzq8bAwj9neZBWSrhvoYI8Bx.  Note that the "overview" video and "designing activities" are in this playlist, but are already on the PhET site.  That said, it might make sense to group together all the "PhET with K12 activities" videos.  
Eventually we will also have a downloadable two-pager to go with each video, or the series, I am working out the details with Kathy.  Don't wait for those to upload the videos, but leave a space for such supporting materials.  
In the past, I have created custom thumbnails for each video (as you can see on the current site) with the PhET logo on the front of the video.  Those were used as thumbnails within YouTube, and also for the images on the right hand side of the screen.  Let me know if you want me to do that or if you will be doing that.

**Comment by ariel-phet** [comment]
@schasteen thanks for having them up on youtube. We will take it from there!

**Comment by schasteen** [comment]
An addendum to this task.  I discussed with Kathy, and she recommends that we link the individual  Expert Recommendations on PhysPort to the appropriate pages in the Teacher area.  I know this area is being redesigned so perhaps these will be placeholders for the moment.  These are aimed at physics, primarily college but not exclusively.

Here are all the ER's:  https://www.physport.org/recommendations/Entry.cfm?T=PhET%20Interactive%20Simulations

Where these might go:
1.  How do I use PhET simulations in my Physics Class?   - in the "Planning to Use PhET"
2.  How do I increase student interactivity when u sing PhET sims in lecture?  - in the PhET in Lecture and/or Interactive Demos
3.  How can I design an effective in class worksheet for PhET? and What are some tips for facilitating PhET with in-class worksheets?  Both with the "using PhET with activities", though the videos are aimed at K12 and these ER's translate that for college.
4.  What are some tips for using PhET in a lab setting?  Possibly in the "using PhET with activities."
5.  What are some tips for using PhET with homework?  Possibly in the "preparing to use PhET."

**Comment by ariel-phet** [comment]
@amyh-phet kicking over to you now that we have some bandwidth on the web dev side to take care of this issue. Lets deal with replacing the main teaching resources video first, and feel free to bring this issue up at a website meeting if you feel like it could use additional input.

**Comment by zepumph** [comment]
Unassigning until @amyh-phet has something for me.

**Comment by amyh-phet** [comment]
@zepumph    I've got this item on the agenda for our website design meeting on 11/1.  I'll update in this issue once we discuss options for these videos.

**Comment by zepumph** [comment]
@amyh-phet do you have any updates for this issue?

**Comment by amyh-phet** [comment]
@zepumph   We will need to add a link to the Tips for Using PhET page under the Tips and Resources for Using PhET and to the list of links on the right side of the page in the gray panel.   The link should read "Video Series: Facilitating PhET Activities in the K12 Classroom". Let's make it the 7th link/bullet point in teh list.  Here's a mockup of changes for the Tips for Using PhET page.   

![tips_for_using_phet_page](https://cloud.githubusercontent.com/assets/13650180/20372091/1475f6ec-ac26-11e6-896f-cf389abb10b0.png)

I need to finalize the design for the new page to house the video series.

**Comment by emily-phet** [comment]
@zepumph - I believe others have taken on the updates to the teacher resources, so I will defer to the rest of the team.

**Comment by zepumph** [comment]
Alright thanks @amyh-phet that's great. Just to be clear I will put this link: https://www.youtube.com/playlist?list=PLU4AnY00Zrzq8bAwj9neZBWSrhvoYI8Bx
into that new video series link and make sure it shows up to the right as well.

What would you like to be done with https://www.physport.org/recommendations/Entry.cfm?T=PhET%20Interactive%20Simulations as I think that that also plays into this issue from @schasteen's comment from July 28th

**Comment by amyh-phet** [comment]
@zepumph    We would like the link to open another page on the website instead of just directing people to the youtube play list.  We looked at a few options of how this might look.  Any chance we could briefly talk over Skype or on Thursday to discuss easiest ways to implement?

**Comment by zepumph** [comment]
That sounds great. Dev meeting often goes until 1:30 or 2. Then I'm free.

**Comment by amyh-phet** [comment]
I'm likely in meetings until 3 pm.  Perhaps 3:15?  I don't think it will take long to discuss.

**Comment by zepumph** [comment]
Alright I'll be around. Just ping me on skype.

**Comment by amyh-phet** [comment]
Looks like I have break from 2:10 to 2:50.  Any chance we could talk then?

**Comment by zepumph** [comment]
Sounds good.

**Comment by amyh-phet** [comment]
@zepumph   Here are the two mockups for possible ways to house the videos on the site.  The preference would be to implement the scrolling video library.  However, we'd like to go with the simplest implementation possible, so if the scrolling video requires a lot of extra work, go with the second mockup.

![tips_for_teachers_k12_video_series_added_tips for using phet copy 2](https://cloud.githubusercontent.com/assets/13650180/20813482/08bd473e-b7d3-11e6-8103-97b704aca24d.png)
![tips_for_teachers_k12_video_series_added_tips for using phet copy 3](https://cloud.githubusercontent.com/assets/13650180/20813483/08c111f2-b7d3-11e6-992e-86096bf4dd76.png)

Don't know if these sites would be helpful as you look at implementing:
http://woosterwebdesign.com/responsive-youtube-player-with-playlist/
https://wordpress.org/plugins/youtube-playlist-player/screenshots/

**Comment by amyh-phet** [comment]
@ariel-phet    Can you comment on the priority of these changes for @zepumph?

**Comment by schasteen** [comment]
BTW, I’m on this thread but haven’t responded since it seems things are going forward… let me know if you need my response to anything.

**Comment by ariel-phet** [comment]
@zepumph it would be ideal to have this done by the new year. It is not super high priority, but it should be a straightforward addition to the website.

**Comment by ariel-phet** [comment]
@schasteen thanks, I think we are good to go!

**Comment by amyh-phet** [comment]
@zepumph   To address @schasteen's comment from Jul 28 about linking to the expert recommendations on the PhysPort site, we need to add a link to existing teacher pages so teachers can find these articles.  The new link should be under the Teacher Tips heading.   Here's a mockup of where a link could be added for the Planning to Use PhET page on Teaching Resources.  

![phys_port_article_link_physport link example](https://cloud.githubusercontent.com/assets/13650180/20851442/c7f91b4e-b89d-11e6-91b4-d07f8f3993fc.png)

Here's a list of pages to update with the text to include and the appropriate link for the article.  Bold text should be the blue link on the page.  The remaining text should be black as it is a description of the link.  My apologies - not sure how to make text colored in a Github issue.

- [ ] Planning to Use PhET page - 3 links to add

- Wording for link on page:   **How do I use PhET simulations in my physics class?**   Tips on how PhET simulations can be integrated into a class.

- Link: https://www.physport.org/recommendations/Entry.cfm?ID=93341

- Wording for link on page:   **What are some tips for using PhET in a lab setting?**    Using PhET in a lab setting has many benefits, such as allowing new possibilities for experiments (such as quantum mechanics), quick repeatability, and making visible the underlying mechanisms.

- Link: https://www.physport.org/recommendations/Entry.cfm?ID=93337

- Wording for link on page:   **What are some tips for using PhET with homework?**   PhET simulations are ideal for use in homework because the simulations are designed to cue students to explore cause-and-effect relationships, even without an instructor present.

- Link: https://www.physport.org/recommendations/Entry.cfm?ID=93288


- [ ] Using PhET in Lecture page

- Wording for link on page:   **How do I increase student interactivity when using PhET sims in lecture?**  Tips on facilitating student discussions, peer instruction, and interactive lecture demonstrations with PhET simulations. 

- Link:  https://www.physport.org/recommendations/Entry.cfm?ID=93340

- [ ] Interactive Lecture Demonstrations page  (same as Using PhET in Lecture page)

- Wording for link on page:  **How do I increase student interactivity when using PhET sims in lecture?**  Tips on facilitating student discussions, peer instruction, and interactive lecture demonstrations with PhET simulations. 

- Link:  https://www.physport.org/recommendations/Entry.cfm?ID=93340

- [ ] Designing Activities for K12 page

- Wording for link on page:  **How can I design an effective in class worksheet for PhET?**  Tips for writing guided activites that support student learning.

- Link:  https://www.physport.org/recommendations/Entry.cfm?ID=93339

- [ ] Facilitating Activities for K12 page

- Wording for link on page:  **What are some tips for facilitating PhET with in-class worksheets?**  Tips for for facilitating activities using PhET -- in a class, lab, or recitation -- in order to get your students to engage with PhET activities.

- Link:  https://www.physport.org/recommendations/Entry.cfm?ID=93338

**Comment by zepumph** [comment]
This last comment will be covered in #543. For this issue I will focus on making the video series page with a  playlist type function in it.

**Comment by zepumph** [comment]
I'm on a branch 'video-series' and will close that branch out with this issue.

**Comment by zepumph** [comment]
@amyh-phet  this is a first pass, let me know what you think. https://ox-dev.colorado.edu/en/teaching-resources/videoSeriesFacilitatingActivities

**Comment by amyh-phet** [comment]
@zepumph   I'm excited that you were able to implement the playlist function here!  Looks really good so far. 

Just a few things I noticed at first glance.   First, the black arrows on the gray circles are a bit hard to see.  Any chance we could make them white instead? Second, any chance the circles could be squares?   Also, is there any way to increase the size of the light gray border under the video thumbnails to accommodate the longer video titles?

**Comment by zepumph** [comment]
@amyh-phet how does that look?

![image](https://cloud.githubusercontent.com/assets/6856943/20979472/4d7c7a3e-bc6a-11e6-8c6a-70061a81b7f0.png)

**Comment by zepumph** [comment]
You can also see the new one up on ox-dev too. Let me know if there is anything else you would like done.

**Comment by amyh-phet** [comment]
@zepumph   Looking great!   Two hopefully minor changes:
I gave you some awkwardly worded copy for above the video.  Can we change it to read:  "A video series that discusses key things to consider when preparing to use and then facilitating activities with PhET simulations.  Focused on K12."

As far as the videos, is it possible to change which video is featured on the page?   The first two videos on the play list appear on other pages in teaching resources, so I'd like to feature the 3rd video on the playlist (the title is [1] Facilitating Activities in K-12: Preparing for...) and have it be the video that loads in the large viewing window.  Let me know if we need to make changes to the playlist for this to happen.

**Comment by zepumph** [comment]
That's an easy fix, but @amyh-phet do you still want the first two videos in the  playlist at all?

**Comment by amyh-phet** [comment]
@zepumph   I think it is okay to leave them in the list in case teachers don't go to the Designing Activities or Facilitating Activities pages.

**Comment by zepumph** [comment]
Alright sounds good. These will go live tonight

**Comment by amyh-phet** [comment]
Excellent!

**Comment by zepumph** [comment]
This is deployed now. Closing
