### ISSUE TITLE
Licensing link returns a page that can't be found

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#466]
On https://phet.colorado.edu/en/licensing/java, the indicated link is either broken or dead:
<img width="620" alt="screen shot 2016-08-10 at 9 46 09 am" src="https://cloud.githubusercontent.com/assets/5863899/17560561/c65a4550-5edf-11e6-853b-4bf93cb50dba.png">

For phetsims/tasks/issues/670.

**Comment by phet-steele** [comment]
It redirects to https://phet.colorado.edu/licensing/java.php

**Comment by mattpen** [comment]
This isn't working on phet-old (figaro) either.  I'm not quite sure where this is supposed to link.  Do you know @phet-steele?

**Comment by phet-steele** [comment]
Not a clue, @kathy-phet care to chime in if you know?

**Comment by jonathanolson** [comment]
Should be showing the LicensingJavaPanel's StaticPage (https://phet.colorado.edu/en/licensing/java) it seems.

**Comment by jonathanolson** [comment]
There's a redirection:
```java
map.put( "/about/licensing.php", "/en/about/licensing" );
```
and /en/about/licensing redirects properly, however earlier in the process (later in RedirectionStrategy), there's:
```java
if ( path.contains( "about/licensing" ) ) {
  return path.replace( "about/licensing" , "licensing/java" );
}
```
which seems to shortcut things, from https://github.com/phetsims/website/commit/d6bf0623c900254bec35ea10deb594ae9b7d8834 related to https://github.com/phetsims/website/issues/80

**Comment by ariel-phet** [comment]
I understand now more... @phet-steele and @mattpen 

This page is basically an HTML page shipped with the java sims as shown here

![java](https://cloud.githubusercontent.com/assets/4051174/18493658/e6e084e2-79ce-11e6-97d4-6336fb281799.PNG)

So that link should redirect to https://phet.colorado.edu/en/licensing/java (since the link currently exists in the java sims) but the link should be removed from the static page on our site. If new java sims have this license (unlikely) since we are not producing more java sims, we will update this page.

so the text "and any additional simualtions..." should be removed along with that link but the redirection should be fixed.

**Comment by mattpen** [comment]
@jonathanolson - Do the java sims pull the content for the licensing page from wicket, or is that duplicated in the svn code somewhere?

In other words, is there some condition I would need to catch to display this link in the wicket code, or can it just be statically removed?

**Comment by jonathanolson** [comment]
> Do the java sims pull the content for the licensing page from wicket, or is that duplicated in the svn code somewhere?

Pretty sure there's a checked-in version.

> In other words, is there some condition I would need to catch to display this link in the wicket code, or can it just be statically removed?

Feel free to modify the website version (I presume).

**Comment by mattpen** [comment]
This was fixed on phet-server
