### ISSUE TITLE
Can't check for sim updates in the installer

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#474]
@mattpen, HTML5 sims can't check for updates in the installer due to this error:

```
XMLHttpRequest cannot load http://phet.colorado.edu/services/check-html-updates. Method post.html is not allowed by Access-Control-Allow-Methods in preflight response
```

Not a huge problem, but I wanted to point it out.

**Comment by kathy-phet** [comment]
I suspect this applies to any offline sim - including those individually downloaded. Can you test, Steele?

**Comment by phet-steele** [comment]
@kathy-phet this error does not appear to be tied to offline sims. In fact, it only occurs when connected to the internet. I tried downloading an individual sim, and it worked just fine.

**Comment by mattpen** [comment]
@zepumph - can you see if this bug is replicable in the new installer? Let me know if we need to work together on fixing this on the website.

**Comment by zepumph** [comment]
@mattpen  it does seem to be happening on the new installer also. I'm getting the same error with html5 sims. On many flash sims there is an error checking for updates as well. This is interesting because I individually download each html sim after the rip of the whole website is complete. Do you think it is a bug on my side or the sim side? I just tested the individual downloads of html5 and flash. It seems like html5 works great, but the check for updates button on the flash doesn't do anything, or a popup shows:

       An error was encountered while trying to obtain version information.
       Please try again later, or visit http://phet.colorado.edu

**Comment by mattpen** [comment]
@zepumph - I'm not quite sure how the html checks work from the sim side.  Let's pair on this when you get back so I can see how the website is behaving when it receives a request from a sim from the installer.

**Comment by zepumph** [comment]
It looks like in joist the line that checks for updates looks like:
e.open("post",u+"//phet.colorado.edu/services/check-html-updates",!0)

but for the installer it is:
e.open("post.html",u+"//phet.colorado.edu/services/check-html-updates",!0)

@mattpen and I think that this is a result of httrack, and we aren't sure why. @jbphet perhaps we thought that httrack wasn't messing with the file when just a folder is downloaded, but it seems to be, I don't know how else this would be happening.  I found that this line of code is also changed in the php version. the best way to proceed would be to fix the js port so that we just individually download each file rather than use httrack for this step.

@mattpen had a good suggestion of using the metadata api to get a list of download links, then it would be simple enough to execute each link into it's appropriate spot. A positive to this approach would be the ability to specify which locales to get. I'm unsure if we care about that, but currently you always get every local of sim, but can choose which locales for the website. May be good to sync them up. Here is an example of the metadat link:
https://phet.colorado.edu/services/metadata/1.1/simulations?format=json&type=html&locale=en

**Comment by jbphet** [comment]
+1 for trying something other than HTTrack, such as curl, for downloading the HTML5 simulations.  The only reason I didn't do this in the PHP version was that HTTrack appeared to work, and I figured that a consistent method of getting the files was easier to maintain.  I would suggest experimenting with alternative methods and if you find that the files aren't altered (which would indicate that they **are** being altered by HTTrack), then go with it.

**Comment by zepumph** [comment]
We will continue this over on in phetsims/installer-builder#45. Closing
