### ISSUE TITLE
nb locale looks weird on the website

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#489]
Similar to phetsims/chipper/issues/329. This issue applies to the website translation table:

<img width="898" alt="screen shot 2016-08-26 at 3 37 44 pm" src="https://cloud.githubusercontent.com/assets/5863899/18021402/6d7eeb6c-6ba4-11e6-8eb5-1c4fbea71365.png">

**Comment by mattpen** [comment]
The name of the locale is being stored in hard code as `Norwegian Bokm�l`.  The � should either be an `å` or an `a`. On the [translated sims page](https://phet.colorado.edu/en/simulations/translated/nb) for `nb`, it is listed as plain ol' `a` in the english version:

![image](https://cloud.githubusercontent.com/assets/11747676/18025136/bef04d14-6bdc-11e6-843a-ddf422407c76.png)

Instead of changing the properties file that holds the `Bokm�l` string, I'm just going to switch to using the same method as the translated sims page (i.e. the [java default](https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#getDisplayName())).

**Comment by mattpen** [comment]
@phet-steele - this should be fixed now.  Anything else to do before deploy?

![image](https://cloud.githubusercontent.com/assets/11747676/18077655/6e894f14-6e44-11e6-93b9-50b93b5e29f6.png)

**Comment by phet-steele** [comment]
@mattpen probably nothing else to do, thanks for the fix.

**Comment by mattpen** [comment]
This was deployed to phet-server.
