### ISSUE TITLE
Create documentation for Metadata API for external use

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#508]
Documentation should be based on original specs in #297 and actual implementation of v1.0.

**Comment by mattpen** [comment]
@jonathanolson - I put up a first draft of the documentation for version 1.0 at https://ox-dev.colorado.edu/en/services/metadata/1.0/documentation, can you please review when you have a chance?

**Comment by jonathanolson** [comment]
- "Query Parameters" instead of "Options" would be nice
- Having the example URL closer to the top (and possibly linked) would be helpful, so people can copy-paste or click to try a request.
- The "Full Object" and "Summary Object" parts are a bit hard to read, since it is hard to tell what parts get replaced in API requests. "id" is Number, but "timestamp" is 0. Both noting the type (number) and some documentation would be helpful, e.g. ```"timestamp": {number} - Seconds since the epoch``` or ```"type": {string} - Either "java", "flash" or "html"```, along with an example value.
- X, Y and Z are helpful to tie together the version string and major/minor/maintenance. Do we need to handle metadata for phet-io versions that would have a suffix?

Looks good!

**Comment by mattpen** [comment]
> X, Y and Z are helpful to tie together the version string and major/minor/maintenance. Do we need to handle metadata for phet-io versions that would have a suffix?

As of today, phet-io versions are not added to the website database so the API would not know about them.  Perhaps we could add this in a new version of the Metadata if we start tracking the phet-io sims in the DB.

**Comment by mattpen** [comment]
v1.0 documentation was delivered to Jamie.
