### ISSUE TITLE
HTTPD errors

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#511]
@markmorlino - We are getting the following error 2-10 times/minute on phet-server, reported in /var/log/httpd/phet-new.colorado.edu-error.log.  It looks like something is trying to contact a service in port 9009, but nothing is listening on port 9009.  Any idea what might be causing this, or if it could cause problems? 

```
[Mon Oct 10 15:12:09.525662 2016] [proxy:error] [pid 65495:tid 139927484364544] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9009 (*) failed
[Mon Oct 10 15:12:09.525682 2016] [proxy_fcgi:error] [pid 65495:tid 139927484364544] [client 127.0.0.1:33726] AH01079: failed to make connection to backend: localhost
```

```
[root@phet-server httpd]# netstat  | grep 9009
[root@phet-server httpd]# 
```

**Comment by ariel-phet** [comment]
@mattpen when did this error begin occurring

**Comment by markmorlino** [comment]
@mattpen 
/etc/httpd/conf.d/phet-new.colorado.edu.conf:  RewriteRule "^/statistics/submit_message(\.php)?" "fcgi://localhost:9009/data/web/htdocs/phet/statistics/submit_message.php" [P,L]
not sure exactly what is supposed to listen on 9009 but this is where it is configured

**Comment by markmorlino** [comment]
@ariel-phet I've been able to see it in the error logs going as far back as August 9th

**Comment by ariel-phet** [comment]
Seems yotta related no?

**Comment by markmorlino** [comment]
it seems related to the php-fpm service not running

**Comment by markmorlino** [comment]
php-fpm had 2 configuration files in /etc/php-fpm.d/ a statistics.conf file and a www.conf file. statistics.conf appears to be what should be running (it listens on port 9009). www.conf appears to be a default config file that gets installed with the php-fpm package. www.conf has a configuration setting to listen on port 9000. Stunnel is already listening on this port so the php-fpm service was not starting. I renamed /etc/php-fpm.d/www.conf to /etc/php-fpm.d/www.conf.listens_on_port_9000 so that it would not get read during the service startup.

there is now someplace for those requests to go:
```
[root@phet-server data]# ss -anlp |grep 9009
tcp    LISTEN     0      128       *:9009                  *:*                   users:(("php-fpm",pid=21121,fd=0),("php-fpm",pid=21120,fd=0),("php-fpm",pid=21119,fd=6))
```

**Comment by mattpen** [comment]
Thanks @markmorlino.  The errors appear to have stopped, this looks great.
