### ISSUE TITLE
Small Bug: Ohm's Law appears twice on Math page

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#531]
Just saw this by chance. Ohm's Law Flash and HTML5 both appear on this page. Not sure why. Seems fine on all sims page: 
https://phet.colorado.edu/en/simulations/category/math

**Comment by kathy-phet** [comment]
No rush here - but seems worth understanding why this bug occurs since I didn't think it was supposed to be possible.

**Comment by amanda-phet** [comment]
Looking at the admin side, Ohm's Law (HTML5) is not listed here, only Ohm's Law is. 
![screen shot 2016-11-16 at 11 12 38 am](https://cloud.githubusercontent.com/assets/7852916/20359572/c1d2c2b8-abed-11e6-9be9-fe4d872054a2.png)

I expect that if I add Ohm's Law (HTML5) this will be taken care of, but we may want to change the way sims are displayed so that it doesn't rely on manual actions like this.

**Comment by ariel-phet** [comment]
Removed "Math" Category from Flash Version of Ohm's Law, issue fixed. Closing
