### ISSUE TITLE
Header Focus Color Change

### ISSUE THREAD

**Issue by emily-phet** [phetsims/website#54]
Can the outline be a light color (like white) for focus objects in the blue header area? For example, it’s hard to tell when the PhET logos are focused, and impossible to tell when the “search” button is focused (for me at least).

**Comment by aaronsamuel137** [comment]
I've updated the focus to be white on the phet and CU logos, as well as the sign-in text. The search box and submit button didn't look very good with white outlines, since they are already white and it was difficult to tell where the outline began and they ended. I decided to go with orange, since it seemed like it had reasonably good contrast with both the white and the blue. I'm open to other ideas if you have them.

I realized after I deployed that I forgot to set the focus for the "skip to main content" to white, as well as the text in the upper right corner for someone who is signed in. I'll make these changes the next time I deploy. In the mean time, feel free to review the changes I have made.

Assigning to @emily-phet for review.

**Comment by emily-phet** [comment]
@aaronsamuel137: Looks good! I find it a little odd that the outline color is changing so much. Here's some ideas of how to help that.
- Can the order of tabbing go PhET Logo, CU logo, Sign in/Register, then Search box? That way you go through all the white outlined options before the orange.
- Can you make a white outline for all focus items with the blue and green border in the center of the page? Those disappear with the grey outline.

Other than that, it all looks great!

**Comment by aaronsamuel137** [comment]
Sounds good. I'll work on that. What browser are you using when you look at the page? I just want to make sure I am looking at the same thing you are when I am making adjustments.

**Comment by emily-phet** [comment]
Safari.

**Comment by aaronsamuel137** [comment]
OK I've made these changes. Assigning to @emily-phet for review.

**Comment by emily-phet** [comment]
Looks wonderful. Thanks!

**Comment by aaronsamuel137** [comment]
Sounds great. I'm going to close this issue for now. Feel free to reopen or start a new issue if other accessibility things come up.
