### ISSUE TITLE
Homepage missing a few translatable strings

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#57]
A translator pointed out that a few strings aren't translatable on the home page right now.
![phet--frie-online-fysikk---kjemi---biologi---geofag--og-mattesimuleringer](https://cloud.githubusercontent.com/assets/5090275/5731468/f60cb4ae-9b40-11e4-831e-6550bd738900.png)

**Comment by aaronsamuel137** [comment]
OK I've made these strings translatable. The strings in the video player were a little more complicated since they are dynamically changed with javascript. However, I think it is working now.

I've made so the video player strings always stay blue instead of changing to purple when they are clicked. I was running into weird behavior where the browser would change from black to blue to purple at different times. Overall, it seemed simpler to just leave them blue since they are not really typical links anyway. Does this sound okay to you? You can look at the updated version on phet-dev.

**Comment by aaronsamuel137** [comment]
Never mind the last comment, I've fixed the link colors act normally. This will be fixed on the next deploy.

**Comment by aaronsamuel137** [comment]
Deployed and appears to be working. Closing
