### ISSUE TITLE
"find us" on facebook should be "like us"

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#58]
The primary focus of a facebook page is "likes" so I think it would be more appropriate to have the phrase "like us" replace "find us" for all occurrences on the website, such as the hover text on the icon and the text in the website footer.

**Comment by amanda-phet** [comment]
Let me clarify; the other social media icons use a verb that implies what we want the user to do once they visit the page ("follow us" on twitter, "pin us" on pinterest), so I thought it would be more consistent to similarly say "like us" on facebook. 

I don't think it is a big deal either way, but it might be nice to be consistent. Perhaps the others could be changed to say "find us" as well? 

@schasteen what do you think?

**Comment by schasteen** [comment]
I personally think it's fine as it is -- I like the "find us" on Facebook, because it makes it clearer that clicking that link will bring you to our Facebook page, rather than automatically "liking" us per se.  But that said, I also don't think it's a really big deal, because I do see Amanda's point that the other icons give such an action (e.g., "Follow us on Twitter" doesn't automatically Follow Us, but it takes you to our Twitter account).

On the pages other than the front page (e.g., http://phet.colorado.edu/en/simulations/category/new), the mouseover says "Share this..." for all the different social media, and I think that that is also nice and clear.  The only thing is that I notice that the Pinterest link just says "Pinterest" when you mouseover, instead of "Share this on Pinterest".  Not sure if that's intentional.  

@kdessau-PhET, do you have any thoughts?

**Comment by kdessau-PhET** [comment]
I agree with your “find” us versus “like” us although I think the accepted term is “like” us.

As for the Pinterest. Share or maybe Follow us on pinterest is better since that is what people are doing. However, if they can “Pin” the sim on their board, then they should be able to do that too


On Jan 20, 2015, at 1:21 PM, Pinterest <pinbot@pinterest.com<mailto:pinbot@pinterest.com>> wrote:

[cid:0D9CD4E9-D44C-4A21-B02F-B3D150AA0B8F@attbi.com]<http://email.pinterest.com/mpss/c/1QA/0NUJAA/t.1ju/bMQD6jaeTA-JEAsza2vW1Q/h0/Gigqz-2Ff2DFUrCtOu1y6fUPNkT2-2BxRVSLYnBCrbSVHfNuR2ZvH-2F5BWBPo9fhYdHU1J8oF9PLAXC7kq5b-2BcvM-2BLXmWY-2F-2Fwqqj-2FF9zwyGFcrfRbFkdjDikbAK-2B-2FFNa5BfNkevu7qQzGw2kxAAMUPe5qwRYYy2vUGLab0aEAeFqQ-2Bzk-3D>
Hi, PhET Interactive Simulations!


2 people started following you.

        [cid:654A48C6-C989-44F1-97ED-098C0965686C@attbi.com] <http://email.pinterest.com/mpss/c/1QA/0NUJAA/t.1ju/bMQD6jaeTA-JEAsza2vW1Q/h1/i41K-2FvbQBVKuIVW29rFpYvVWCnJNZ8S7v37ji09Avhv5x-2FB19ayaeeQRdYnsvc26p5V4GDbkCsOarK028fMlj2rew1yK4WDKL0HQxKcwnMEpGJWs8JQAcoulP1odgkgngQP6Vh6XRckgljV3uYNJnuATd-2BW-2Fkn4V3eSBZRFaJSHf0s-2FsHmkPQFeLHUhutcpfjbxXBUh7DOpKvE8wY9oIng6zScogZiZx0gQY1xCsWvltPpHNfp8Ncj0tHbyf-2FY-2BpW-2FktFjviUpzM8IS3jTRKtB8vRqKZtrF9RaAmTRg2pXyXX5EK-2FmQvn9ExDAwITw0SqVNEsD2emIcyE4Y9CTU4i-2F6oSlEr-2BLoblbli-2FvJu-2B-2F0Ysz-2FNu-2BZZSm6EoPU9UUYCRMpKtZU8oOgrnx2ISsH85-2BmrJDshMQ7N-2Bza4Yog-2BqIiHpCEQNGRNiffkmuchYDP6r3es8e3Lb6dYuBBEIbCY0BpbswKmPFYrj-2B1txUnVqOjIvlFXJVRdCLPfmPOaGz59AWBpeSTzTvmmzZarm4sxEoopQgK1h-2FoGv5PwJ22xDTY-3D>



Fabio Zanoni<http://email.pinterest.com/mpss/c/1QA/0NUJAA/t.1ju/bMQD6jaeTA-JEAsza2vW1Q/h2/i41K-2FvbQBVKuIVW29rFpYvVWCnJNZ8S7v37ji09Avhv5x-2FB19ayaeeQRdYnsvc26p5V4GDbkCsOarK028fMlj2rew1yK4WDKL0HQxKcwnMEpGJWs8JQAcoulP1odgkgngQP6Vh6XRckgljV3uYNJnuATd-2BW-2Fkn4V3eSBZRFaJSHf0s-2FsHmkPQFeLHUhutcpfjbxXBUh7DOpKvE8wY9oIng6zScogZiZx0gQY1xCsWvltPpHNfp8Ncj0tHbyf-2FY-2BpW-2FktFjviUpzM8IS3jTRKtB8vRqKZtrF9RaAmTRg2pXyXX5EK-2FmQvn9ExDAwITw0SqVNEsD2emIcyE4Y9CTU4i-2F6oSlEr-2BLoblbli-2FvJu-2B-2F0Ysz-2FNu-2BZZSm6EoPU9UUYCRMpKtZU8oOgrnx2ISsH85-2BmrJDshMQ7N-2Bza4Yog-2BqIiHpCEQNGRNiffkmuchYDP6r3es8e3Lb6dYuBBEIbCY0BpbswKmPFYrj-2B1txUnVqOjIvlFXJVRdCLPfmPOaGz59AWBpeSTzTvmmzZarm4sxEoopQgK1h-2FoGv5PwJ22xDTY-3D>


        [cid:277B8A5A-EDEB-4F9E-B619-087DDA4ECE84@attbi.com] <http://email.pinterest.com/mpss/c/1QA/0NUJAA/t.1ju/bMQD6jaeTA-JEAsza2vW1Q/h3/i41K-2FvbQBVKuIVW29rFpYvVWCnJNZ8S7v37ji09Avhv5x-2FB19ayaeeQRdYnsvc26p5V4GDbkCsOarK028fMlj2rew1yK4WDKL0HQxKcwnMEpGJWs8JQAcoulP1odgkgngQP6Vh6XRckgljV3uYNJnuATd-2BW-2Fkn4V3eSBZRFaJSHf0s-2FsHmkPQFeLHUhutcpfjbxXBUh7DOpKvE8wY9oIng6zScogZiZx0gQY1xCsWvltPpHNfp8Ncj0tHbyf-2FY-2BpW-2FktFjviUpzM8IS3jTRKtB8vRqKZtrF9RaAmTRg2pXyXX5EK-2FmQvn9ExDAwITw0SqVNEsD2emIcyE4Y9CTU4i-2Befmn-2Fp5SdYApMDkzaOD9t-2F5E9HP-2BVSbRw0jJA5jDPZTAuRi52A8kyN-2Bl1CK4PFjEbpuCqs9Ykd6iNGttwuJL5Z3DheEpqi-2B1WB4bE0V2z10YH57cKSXOk-2B5Fy7CzH4M0fRFFlmccvlPr-2FxSRnGVFZTuy8V-2FpEWz28-2FNn6pEyeRshGWc2IivSZ-2Bl5wrYj1xBjkttTuvWWOq-2F22EL5ci3q0-3D>




Kendra Nelson<http://email.pinterest.com/mpss/c/1QA/0NUJAA/t.1ju/bMQD6jaeTA-JEAsza2vW1Q/h4/i41K-2FvbQBVKuIVW29rFpYvVWCnJNZ8S7v37ji09Avhv5x-2FB19ayaeeQRdYnsvc26p5V4GDbkCsOarK028fMlj2rew1yK4WDKL0HQxKcwnMEpGJWs8JQAcoulP1odgkgngQP6Vh6XRckgljV3uYNJnuATd-2BW-2Fkn4V3eSBZRFaJSHf0s-2FsHmkPQFeLHUhutcpfjbxXBUh7DOpKvE8wY9oIng6zScogZiZx0gQY1xCsWvltPpHNfp8Ncj0tHbyf-2FY-2BpW-2FktFjviUpzM8IS3jTRKtB8vRqKZtrF9RaAmTRg2pXyXX5EK-2FmQvn9ExDAwITw0SqVNEsD2emIcyE4Y9CTU4i-2Befmn-2Fp5SdYApMDkzaOD9t-2F5E9HP-2BVSbRw0jJA5jDPZTAuRi52A8kyN-2Bl1CK4PFjEbpuCqs9Ykd6iNGttwuJL5Z3DheEpqi-2B1WB4bE0V2z10YH57cKSXOk-2B5Fy7CzH4M0fRFFlmccvlPr-2FxSRnGVFZTuy8V-2FpEWz28-2FNn6pEyeRshGWc2IivSZ-2Bl5wrYj1xBjkttTuvWWOq-2F22EL5ci3q0-3D>
789 pins · 19 boards



See all of your followers on your profile page.<http://email.pinterest.com/mpss/c/1QA/0NUJAA/t.1ju/bMQD6jaeTA-JEAsza2vW1Q/h5/i41K-2FvbQBVKuIVW29rFpYvVWCnJNZ8S7v37ji09Avhv5x-2FB19ayaeeQRdYnsvc26p5V4GDbkCsOarK028fMlj2rew1yK4WDKL0HQxKcwnMEpGJWs8JQAcoulP1odgkgngQP6Vh6XRckgljV3uYNJnuATd-2BW-2Fkn4V3eSBZRFaJSHf0s-2FsHmkPQFeLHUhutcpfjbxXBUh7DOpKvE8wY9oIng6zScogZiZx0gQY1xCsWvltPpHNfp8Ncj0tHbyf-2FY-2BpW-2FktFjviUpzM8IS3jTRKtB8vRqKZtrF9RaAmTRg2pXyXX5EK-2FmQvn9ExDAwITw0SqVNEsD2emIcyE4Y9CTU4i78XTqwlmnV-2BWPO2-2BB7XWj96Gh9twPTGSkDfkf7dSxZcSgGUWOJd-2FHFKgK44h6x4fAZPUMOx4kcdInJ6GLdaAckEnFJ4w-2BnlQURAA0oej-2BW9Dt7Qr5sJY9K9iQ2d5bG5tScSG5vLbFtRefJ3G8EDRIfZmHS5PW-2BWvHUYcFA17V26l8XxJIsCB0kfBgApeDZT9vh23x-2FlULMCIe3QGuIDQBS6IoDQmcGudUXL3CJgXlxk>

Happy pinning!


This email was sent to Kathryn.Dessau@colorado.edu<x-msg://85/Kathryn.Dessau@colorado.edu>.
Don't want to receive this type of email? Unsubscribe<http://email.pinterest.com/mpss/c/1QA/0NUJAA/t.1ju/bMQD6jaeTA-JEAsza2vW1Q/h6/i41K-2FvbQBVKuIVW29rFpYn-2B6vzMUUDlDNlQsnNtwIxeaJqbhBxIXDR2Z1N2n120ltgZxFvHtddct1ChcVDzibIswHpt7t16-2BkGyM4-2FsF223p6oGPhSG8qKuttebbt9bhduRgOmPpB99s0zcI6OI4lf4oJWGSueIvDCfhVk-2F3wvxSQYZvd6isLJX6KT8vJqZIql2vPvDG1OliyHOLk7gjTRBv26vILz1-2BK33MYho4m0n2zBz6Vt6Xicy-2FlHpakQsoWI2jYBP2oDw0RFkqqRQgnDB0ZNhwT0K46dRWhjHD-2B0vrlUViM3aaOTAk9gKwyYnHjwrWa0j27eOdUSA6m82t9u1wIrUENum1J56iB6lZKTDtJ8S2FfO5FF-2F8WpxhrvxWNwSb-2BKL9StCgbVovSkpijeoWsQ3RCQmBEoFx5tChpE-2Bx9d8-2FZ2mH59nnde5rPsqzYy8UaF-2FJEu5X-2Fw4VvvbjlrqFboqsvbHqNl4pwDguMlh6M9-2BIlPgNYGe5TKvEmsAZpqCL62C8p6xgmrRDr7UtmYRn-2BQsv41PZCecGQEIkDW6Hv-2BjsZsQ0IDydRE9pxvdZ7lyc1XG9EtFfmnAvvamCx9O-2FqWzZCdVIzD7mHc3d-2F64KKUTZtBJR2ExPCkRyiXYB7RqoLYSDI6yB5k2XNdbvvcErk08Cfepddlx-2BLjSZQgRqexk6LATe1gvTDqMjPPP0FK1b8B3PcOQNQweRnYOBWMpK383t52oAvifmccSAoxtsWvaJAzbwbBDq7T0y-2Fv8clpLxCE9On6JvyH424Wd3fTM8QAeK8m84a9GVX0TLROynReO1XzJ7dtrE86NCXyWAQLOrgauGwuLnh3-2BxEsc0fw-3D-3D>.
Have a question? Visit our Help Center<http://email.pinterest.com/mpss/c/1QA/0NUJAA/t.1ju/bMQD6jaeTA-JEAsza2vW1Q/h7/i41K-2FvbQBVKuIVW29rFpYhpLoEkWSAxLWG7kTxLyJGDge2l-2FOO08ZfBqBrcweuwMa32ymcf7JVunhktvbDwSlX2XeZrKAlPYTjS5d3d7cjflxvqJBBAcUKHuogxlihOL588fagD5M-2BzKqjLc4JxIkJ6ggDRUzRkCPNnWamqmoVR5pEZWQ0mXe-2FJsYOpuIF59>.

©2013 Pinterest, Inc. | All Rights Reserved
Privacy Policy<http://email.pinterest.com/mpss/c/1QA/0NUJAA/t.1ju/bMQD6jaeTA-JEAsza2vW1Q/h8/i41K-2FvbQBVKuIVW29rFpYp7zD3Cud38Adcdr-2FcJurqrPiVF2o4uQXkJ4x1Cm-2Bs31> | Terms and Conditions<http://email.pinterest.com/mpss/c/1QA/0NUJAA/t.1ju/bMQD6jaeTA-JEAsza2vW1Q/h9/i41K-2FvbQBVKuIVW29rFpYp7zD3Cud38Adcdr-2FcJurqqjRixyf2ao-2FyxKa3-2BfhJu3>




On Jan 20, 2015, at 1:33 PM, schasteen <notifications@github.com<mailto:notifications@github.com>> wrote:


I personally think it's fine as it is -- I like the "find us" on Facebook, because it makes it clearer that clicking that link will bring you to our Facebook page, rather than automatically "liking" us per se. But that said, I also don't think it's a really big deal, because I do see Amanda's point that the other icons give such an action (e.g., "Follow us on Twitter" doesn't automatically Follow Us, but it takes you to our Twitter account).

On the pages other than the front page (e.g., http://phet.colorado.edu/en/simulations/category/new), the mouseover says "Share this..." for all the different social media, and I think that that is also nice and clear. The only thing is that I notice that the Pinterest link just says "Pinterest" when you mouseover, instead of "Share this on Pinterest". Not sure if that's intentional.

@kdessau-PhET<https://github.com/kdessau-PhET>, do you have any thoughts?

**Comment by oliver-phet** [comment]
I would vote for the text being standardized, so "Like us on Facebook" rather than "Find". Find isn't a common term on facebook.

**Comment by aaronsamuel137** [comment]
OK I've changed "Find us" to "Like us". It's easy to change back if people don't like it.

I've also changed "Pinterest" to "Share this on Pinterest" on the non-homepage pinterest icons, which is consistent with the other mouseovers on those pages.

**Comment by ariel-phet** [comment]
The rollovers all work nicely, but for consistency now the footer should say "Like us" whereas it still says "Find us"

**Comment by aaronsamuel137** [comment]
Good call. I've updated this string to say "like us"

**Comment by ariel-phet** [comment]
Closing
