### ISSUE TITLE
Possible to login in from http://, makes session cookie visible

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#66]
While working on the translation utility, I ran across a case where the JSESSIONID cookie appears in the URL.  This happens when a user logs into to the web site from http instead of https.  @jonathanolson pointed out that if someone sniffed this over an unencrypted wireless link, they could use the cookie value to log in as that user.  We should probably set things up so that users can’t log in from http, probably just automatically redirecting to https:// when accessing the login page.

**Comment by aaronsamuel137** [comment]
As far as I can tell, this has been an unnoticed issue on the website for awhile now. It seems like anytime that a user is redirected to the login page instead of going there themselves the JSESSIONID appears in the url AND the site is browsed over http instead of https.

I'll see if I can figure out a way to prevent this from happening.

**Comment by aaronsamuel137** [comment]
This issue has been fixed. However, a new issue was introduced where the nav locations are no longer preserved on the login page before the redirect happens. Since this is a more minor issue, the decision was made to go ahead and push the security fix and worry about addressing this later. I'll create a new issue to track this.
