### ISSUE TITLE
Search bar is throwing out internal error

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#70]
Type "build" in the search bar and hit enter. Receiving:

Internal error occurred

Please contact us at phethelp@colorado.edu for assistance or to report the error.

Seems like words that are included in a sim name cause the error. But the text "buil" will not error.

**Comment by aaronsamuel137** [comment]
It looks like this error has to do with a missing row in the contributions database. The logs complain about a missing row for contribution id 3870. Interestingly, this works fine on phet-dev, but not on phet.

http://phet-dev.colorado.edu/en/contributions/view/3870

http://phet.colorado.edu/en/contributions/view/3870

I can't figure out why this may be, even when I sync the phet-dev database to the phet database, it still works on phet-dev but not on phet.

This also explains why it only happens when there is a key word from a sim name. This page appears to have all of the sim names written out on it.

Searching the figaro data base for contribution id 3870 finds no result, though it finds it fine on simian. I have no idea why this might be.

I'll look into it some more. @jonathanolson do you have any ideas?

**Comment by aaronsamuel137** [comment]
The page on phet-dev has a comment from 12/13/14, so theoretically it must have been appearing properly at that point on figaro.

**Comment by aaronsamuel137** [comment]
I still have no idea why the contribution 3870 is mysteriously missing from the database, but the search issue should be fixed now.

Assigning to @oliver-phet for review.

**Comment by jonathanolson** [comment]
Users have permission to delete their own activities. Maybe that happened?

**Comment by oliver-phet** [comment]
I think 3870 may have been my activity. Ariel had requested I delete it since we now have the ‘By Device’ category on the site.
Also, it may be messing up the search because the activity had every sim listed – so almost any search would find that activity.

**Comment by aaronsamuel137** [comment]
I'm going to close this issue since the search bar error has been fixed by catching an ObjectNotFoundException.

There is still a potential issue here involving the fact that the code or database was still looking for a contribution that had been deleted. I'll start up another issue to track this.
