### ISSUE TITLE
Update 'Troubleshooting' pages with #qXX URL behavior (like FAQ page)

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#74]
@aaronsamuel137 Can you add the URL behavior for each of the 3 troubleshooting pages (Mac, Windows, Tablets) so that when a question is clicked it adds the q# to the url. I can then send specific links to users that address the issue they are encountering.

**Comment by BrianNewsom** [comment]
Fixed with https://github.com/phetsims/website/pull/89.  Let me know what you think!

**Comment by aaronsamuel137** [comment]
There are a few issues with the troubleshooting pages where the triangles do not switch when clicked.

I have updated TroubleshootingMacPanel to fix this and show the correct pattern to use. We also need the a tag hrefs to point to the headers here, so @oliver-phet has a link he can give people to specific issues. Following the pattern in TroubleshootingMacPanel should take care of this.

Follow the same pattern in the FAQ page too. Thanks!

Also - I preemptively merged this into master (sorry!), so just fix these files on master. I won't do a redeploy until these are fixed.

Assigning to @BrianNewsom.

**Comment by aaronsamuel137** [comment]
Also - pull from svn and the build tools should now minify the expandable text with the rest of the js. Now we can get rid of the script imports.

**Comment by BrianNewsom** [comment]
Updated both of these as I think you want.  Let me know if anything is weird.  Sorry I didn't quite get it the first time, I was trying to follow your example but I think a few things changed!

**Comment by aaronsamuel137** [comment]
Nice work Brian, thanks! Sorry for changing things on you a little bit.

@oliver-phet, take a look on phet-dev and see if this is doing what you need. The page doesn't automatically scroll to the question when you click a link - since this looked weird when we tried it on the new sim pages - but you can still link to questions like so: http://phet-dev.colorado.edu/en/troubleshooting#q5-header

The page should jump to that location and automatically open the text. The url hash doesn't automatically  change when you click a link, but you can find out what the url hashes are for each link easily by mousing over them in chrome and seeing what the link text says.

**Comment by aaronsamuel137** [comment]
Assigning to @oliver-phet for review.

**Comment by oliver-phet** [comment]
I can't seem to expand the text of a link... is it functional yet? I would like to be able to send a user a link to the troubleshooting issue and have the text expanded for that issue. Is that possible?

**Comment by ariel-phet** [comment]
Try doing a "hard refresh" on your browser @oliver-phet

**Comment by oliver-phet** [comment]
Yep that did the trick. Thanks @ariel-phet 
@aaronsamuel137 and @BrianNewsom This is looking awesome. Unless there is something else that needs added, I think this is ready.

**Comment by aaronsamuel137** [comment]
Sounds good. I have deployed to figaro. Closing.
