### ISSUE TITLE
Dialog for login (overlay instead of taking user to a separate window)

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#75]
We have discussed having a login dialog appear on the site instead of taking the user to a separate window (so the dialog is overlayed on the page, and the page opacity is reduced) much like on pintrest or other modern sites. 

This would be good to work on as a project for the design team. @aaronsamuel137 said it would be around a 5-10 hour implementation project (plus pixel polishing).

@amanda-phet -- lets put this on the agenda at some point for website design meeting.

**Comment by amanda-phet** [comment]
Here is the latest mockup of this dialog box. At status, we decided that this should probably roll out around the same time as the new sim pages if @aaronsamuel137 can get it up and running, since it is relevant to accessing content on sim pages. 

![screen shot 2015-03-12 at 11 05 23 am](https://cloud.githubusercontent.com/assets/7852916/6623313/c1b57b8e-c8a7-11e4-85f4-44a0a1468292.png)

**Comment by aaronsamuel137** [comment]
I've made a first attempt at this. I expect there may be bugs since this touches a fair amount of the code. Let me know what you think so far.

It seems like we will need to keep our old login page as well. What if somebody has a direct link to a page that requires login? We won't be able to do a popup in this case, so right now it keeps the old behavior of redirecting to the login page.

Assigning to @ariel-phet and @amanda-phet for review and comments.

**Comment by ariel-phet** [comment]
@aaronsamuel137 can you give more detail as to why you wouldn't be able to do a popup in the case you are suggesting? For instance, if I am not logged in, and I click on "Share your Activities" the Sign in dialog appears (which is great behavior).Couldn't it just take you to the page with the Sign in dialog overlayed?

If not it does not seems like a big deal, but maybe we adjust the look of the sign in page to match this dialog...just so it feels more consistent?

**Comment by ariel-phet** [comment]
Oh, and two "pixel polish" comments

1. Remover the underlines from the "Forgot password" and "Register" links....just looks cleaner and more modern in the mockup.

2. The "Sign in" button should have a slight round on the corners to match the style of the other flat buttons.

**Comment by amanda-phet** [comment]
I am also wondering about why the popup wouldn't work in the scenario above. 

I agree with @ariel-phet 's pixel-polish issues above. We are getting rid of underlined links and the button should match the style of our other buttons.

**Comment by aaronsamuel137** [comment]
OK so it sounds you want to be redirected to the correct page first, and then have the popup come up. I think this can be done, but there are a few complications because the popup is triggered by javascript and I'm not sure what we'd want to happen if they have javascript disabled.

I'll look into it and let you know what I come up with.

**Comment by aaronsamuel137** [comment]
Also, doing it this way will require much more changes to the code base, since most of the pages that require login will break if you go to them before a user is logged in.

I think it can be done, but it will be more of a major restructuring of the code. I'l have to spend some time architecting a bit to figure out the best way to go about this. It might be useful to discuss pros and cons in person at some point before diving in too deeply.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - I think your original suggestion is fine for now. Basically send them to the login page (other sites that follow this convention, such as banks, or email programs), and it is not worth it to restructure the code.

However, it would be good to make the Sign in page look a bit more like the dialog box.

@amanda-phet - can you make a mockup of an improved look sign in page?

**Comment by amanda-phet** [comment]
I agree, this is a major change that I didn't anticipate. It might be more appropriate to make this kind of change at a later point.

**Comment by ariel-phet** [comment]
Plus...as @aaronsamuel137 pointed out, it will only be if someone has a direct link to a page bookmarked

**Comment by amanda-phet** [comment]
I was just thinking that we should update the look of the sign in page. Since we're doing the activity submission and register pages, I think we should stick with a consistent look.

**Comment by amanda-phet** [comment]
![screen shot 2015-03-25 at 11 58 57 am](https://cloud.githubusercontent.com/assets/7852916/6831523/6727f3ba-d2e6-11e4-9e71-18ff858e8b7d.png)

**Comment by ariel-phet** [comment]
I have to say...I really like the dialog when I use it currently. It feels very natural when you click the sign in button, or when you are not signed in and click on one of the side bar navigation links that require sign in.

**Comment by amanda-phet** [comment]
I didn't actually experience that behavior! When I'm on a sim page and want to share an activity, it takes me to the sign in page. But if I go to Teacher Resources > Share Activity, I get the dialog. It IS nice!

**Comment by aaronsamuel137** [comment]
The link on the sim page should make popup instead of redirecting. I'll fix this. Let me know if you know of any other internal links that still redirect to the sign in page.

**Comment by aaronsamuel137** [comment]
I've added the new login page layout. Assigning to @amanda-phet for review. Should I redo the register page with a similar style for the input boxes too?

Also, are there any other thoughts about the login dialog in general?

**Comment by amanda-phet** [comment]
Can you suggest a route to get to the new login page? I keep getting the dialog box (which is awesome!). 

Don't do the register page yet- I still have to meet with Kathy about the changes to that page.

**Comment by aaronsamuel137** [comment]
Try phet-dev.colorado.edu/en/teaching-resources/submit-activity

**Comment by amanda-phet** [comment]
That worked. It looks good to me, and that is definitely the same style we will want to use on the registration and activity submission pages. Just two tweaks:
* The "Remember me" checkbox doesn't seem aligned with the text
* Let's make the SIGN IN button (for the page and the dialog) match our other buttons in size and with bold text
![screen shot 2015-04-06 at 12 54 28 pm](https://cloud.githubusercontent.com/assets/7852916/7010119/4377f0e4-dc5c-11e4-9605-292dada22b65.png)

**Comment by aaronsamuel137** [comment]
Checkbox and submit button are updated. Assigning to @amanda-phet for review

**Comment by amanda-phet** [comment]
Looks good on Chrome, but Firefox always seems to have issues. 
Firefox button: 
![screen shot 2015-04-08 at 9 14 24 am](https://cloud.githubusercontent.com/assets/7852916/7049624/ca021170-ddcf-11e4-9706-b70afe9aca69.png)

Chrome button: 
![screen shot 2015-04-08 at 9 15 44 am](https://cloud.githubusercontent.com/assets/7852916/7049631/db102fec-ddcf-11e4-958b-460b6ae530ef.png)

I assume this will get sorted out so I'll go ahead and close the issue.
