### ISSUE TITLE
"By Grade Level" category images could use some work

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#79]
The "By Grade Level" link brings you to a page that has pictures that may not be very meaningful to teachers

http://phet-dev.colorado.edu/en/simulations/category/by-level

It would be good to replace these four pictures of pictures more representative of these grade levels (perhaps pictures of people in classrooms). 

@amanda-phet - we can discuss as a small group sometime, and it would be good to get you access to all our photo resources of classroom use for which we have media releases.

**Comment by amanda-phet** [comment]
While the current images might not be "meaningful", the screenshots change a lot in complexity. The younger sims have more whitespace and primary colors, while the college level look dauntingly advanced with gray and graphs. 

However, I agree that some photos of students is the way to go. We have some really nice images of classroom use. I'm imagining an elementary student on an iPad, middle school students in groups, high school students in a computer lab, college students in a lecture- all showing off a sim somewhere.

**Comment by ariel-phet** [comment]
Those sounds like great suggestions to me. Do you want to choose a candidate photo for each?

**Comment by amanda-phet** [comment]
@ycarpenterphet Do you have any photos of a sim being used in a lecture? Ideally Carl or Mike or Kathy (I think I've seen a photo like this somewhere!) standing in front of a projected sim in a lecture setting, maybe some students looking at them. 

@kathy-phet We do not have a great elementary-age photo. Can we use your children to pose a photo? It would be great to show young kids using a sim on an iPad and we currently do not have a great option.

**Comment by kathy-phet** [comment]
Tonight happens to be science night at Bear Creek Elementary, and there is a PhET station. I can bring my camera and take some photos - and then I can work on contacting the parents to get releases.

**Comment by ycarpenterphet** [comment]
We certainly do have a variety of images of PhET in use at the college/university level (someone lecturing with a sim demo on the big screen, or a lecture hall with students working in groups at laptops, or students using sims in labs).

I only have cropped or lower-resolution images that I've used in presentations. @schasteen will probably be the best resource for knowing the media images we have for this purpose (and specifically, which have appropriately signed releases for this use case).

I admit, I'm a little loathe to use a lecture image since I don't really want to immediately have people think of this as the only mode of use for sims in college - but I recognize that this is probably the most recognizable image of "university" teaching and learning.

**Comment by schasteen** [comment]
If you tell me which images you want and, most importantly, what folder you got them out of in the PhET Backup 2 drive, I can tell you if I have information on releases.  Some of them (not many) have release information in the folder.  Some I was not involved with and may not know anything.

**Comment by amanda-phet** [comment]
@schasteen I can email you the photo information to find out if there are releases. However, I found that phetbackup2 just didn't have many to choose from, and definitely not any undergraduate lectures. Are there more photos somewhere that haven't made it to phetbackup2? In particular, I think I've seen some floating around of CU faculty that were not on the server (so perhaps they didn't have releases).

**Comment by schasteen** [comment]
PBU2 has all the still images that we have; I know there are some really nice ones with Carl Wieman in UG, and some good ones in K12 (especially in the "students with sims" folder).  . If you're having trouble finding ones of college, the best might be if you took a screenshot from the video footage.  All the more recent stuff (say, after 2010) is in HD, and so a screenshot will look very good.  We don't take a lot of still images during filming, so the photos folder is a hodgepodge of times when photos were taken for various purposes, rather than a really complete set of photos that were deliberately taken.  The ones labelled "screenshot" in "students with sims" are from screenshots.

Also, in Reimagine Eduation / photos / classroom use are a few screenshots in college.

Here is our uber sheet of all the footage taken, so you can easily see what's in each video shoot.  If you want something non-lecture based, there are several good ones of students using them in labs.
https://docs.google.com/spreadsheets/d/1FIAOcnADU2mGqQ7LFfjhk1yqlD7-MDnPolbUzYAnVs8/edit#gid=2

**Comment by amanda-phet** [comment]
We have picked some images, so I will email them to @aaronsamuel137 to upload at some point.

**Comment by aaronsamuel137** [comment]
New photos are up: http://phet-dev.colorado.edu/en/simulations/category/by-level

Assigning to @amanda-phet for review

**Comment by amanda-phet** [comment]
Looks perfect to me. Assigning to @ariel-phet to confirm and close this issue.

**Comment by ariel-phet** [comment]
Yeah, I think these look great! 

@aaronsamuel137 please push to the main website when you get a chance, please close the issue once deployed

**Comment by aaronsamuel137** [comment]
Deployed. Closing
