### ISSUE TITLE
Adding a "PC/Mac" subcategory for the By Device category

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#81]
@oliver-phet has mentioned that is might be nice to have a "PC/Mac" subcategory in our "By Device" category.

I think this change makes most sense to implement when we have the new HTML5 sim pages up. (Since all screenshots will then be uniform, and each will have a badge with the code base). Not a major priority, but I wanted to get an issue started.

**Comment by ariel-phet** [comment]
@arouinfar suggested that we make these categories separate and additionally at the top of the Mac category have a link to the troubleshooting (since many people have difficulty opening our java sims on a mac)

**Comment by arouinfar** [comment]
This could be alleviated by the creation of a YouTube video describing how to run Java sims on a Mac (see https://github.com/phetsims/tasks/issues/195)

**Comment by zepumph** [comment]
I can start working on creating a Mac/PC page, or two separate ones. @ariel-phet  do you want to hash out a more concrete to do list for this enhancement?

**Comment by aaronsamuel137** [comment]
We'll need a new icon on the "by-device" page (http://phet.colorado.edu/en/simulations/category/by-device) to complete this issue. After that, it shouldn't take long to complete.

Also, would this category include all of our sims, or are there ones that should be left out?

Assigning to @ariel-phet to address these two concerns before I can work on this.

**Comment by ariel-phet** [comment]
@arouinfar @oliver-phet @amanda-phet what is the feeling here about mac/pc category or splitting those? With the upcoming help center are most of the troubleshooting concerns alleviated?

**Comment by arouinfar** [comment]
@ariel-phet, I don't really have a preference. Now that Molecule Shapes is in HTML5, the only non-Mac sim is Plate Tectonics, so the PC and Mac categories would be virtually identical.

**Comment by amanda-phet** [comment]
The fact that they would be identical is why I've always thought it was unnecessary. Once we have true filtering this may be a more useful category so that mac users don't accidentally find Plate Tectonics, but I'm not sure how this is beneficial right now.

**Comment by oliver-phet** [comment]
I think it would be nice to clear up the Plate Tectonics Mac issue. We still get a lot of phethelp emails about this and there is no way for a user to know that the sim won't work on a Mac (unless a user reads troubleshooting info before trying to run a sim... I'm sure that happens)
I think it would be best to do a single 'PC/Mac' category, but add something to the sim page to notify Mac users about Plate Tectonics incompatibility.

**Comment by amanda-phet** [comment]
I think a notice of some kind on the Plate Tectonics sim page itself is the best way to communicate that it does not run on a Mac. Using the by device category won't fix that issue.  

@oliver-phet Can you please explain the reasoning for a PC/Mac category? I'm still not sure I see a use-case for it, since it will be a list identical to All Sims (http://phet.colorado.edu/en/simulations).

**Comment by oliver-phet** [comment]
I agree about the Plate Tectonics notice. 

I remember thinking this wasn't a huge priority and I think that's why we didn't add this category at the same time as the others. In my opinion it just makes it perfectly clear to users which sims work on which devices. Since 'By Device' isn't currently a filter and is rather a category, I thought it might be good to have a PC/Mac category, which also makes it clear that HTML5 sims are supported on PC/Mac (along with Java/Flash)

**Comment by ariel-phet** [comment]
Seems time to close this issue. We have fixed plate tectonics with an individual page solution, and eventually we will have filtering enabled on the website.
