### ISSUE TITLE
Change "For Teachers" page to "Teacher Resources"

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#85]
We have a new "For Teachers" section on the newest sim pages with materials like activities, tips, and video primers. Our main "For Teachers" page is really a set of resources, so I think the name of that page should be changed to "Teaching Resources", and if possible the url should also change to http://phet.colorado.edu/en/teaching-resources.

**Comment by ariel-phet** [comment]
And the sidebar navigation should change as well.

**Comment by aaronsamuel137** [comment]
Should this be a change to master, or should this get deployed with the new sim pages?

**Comment by ariel-phet** [comment]
It should get deployed with the new sim pages

**Comment by aaronsamuel137** [comment]
A few concerns with this:

1. Around 20 urls will be changed if we change the "for-teachers" url to "teaching-resources", since there are about 20 pages that use this prefix (contribution pages, tips pages, workshops pages, etc.). Should we look into redirecting the old urls to the new ones?

2. I assume that the correct title is "Teaching Resources", not "Teacher Resources", but correct me if I'm wrong. (It says "Teacher Resources" in the issue title, but "Teaching Resources" in the the body)

**Comment by ariel-phet** [comment]
@amanda-phet - can you comment on the title (Teaching Resources vs. Teacher Resources)

@aaronsamuel137 - I think it will be OK to change the urls...these pages are not widely used yet ( I think if you look at the analytics you will see a small number of hits), so I think it will be a very small usecase of people who have book marked them.

**Comment by ariel-phet** [comment]
And I see the confusion on the title, since there is conflict between the title in the issue name and the title suggested in the comments

**Comment by amanda-phet** [comment]
I meant "Teaching Resources" but I don't actually have a preference either way.

**Comment by ariel-phet** [comment]
Lets go with "Teaching Resources" it has better contrast to the "For Teachers" section title that will be on the sim pages

**Comment by aaronsamuel137** [comment]
OK I've gone with Teacher Resources. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks good to me!
